// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: keyserver/v1/service.proto

package keyserverv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GenerateKeyRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TenantId       string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	UserId         string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	OrgId          string                 `protobuf:"bytes,3,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	Scopes         []string               `protobuf:"bytes,4,rep,name=scopes,proto3" json:"scopes,omitempty"`
	IssuedByUserId string                 `protobuf:"bytes,5,opt,name=issued_by_user_id,json=issuedByUserId,proto3" json:"issued_by_user_id,omitempty"`
	ExpiresAt      *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	SharedDb       bool                   `protobuf:"varint,7,opt,name=shared_db,json=sharedDb,proto3" json:"shared_db,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GenerateKeyRequest) Reset() {
	*x = GenerateKeyRequest{}
	mi := &file_keyserver_v1_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateKeyRequest) ProtoMessage() {}

func (x *GenerateKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_keyserver_v1_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateKeyRequest.ProtoReflect.Descriptor instead.
func (*GenerateKeyRequest) Descriptor() ([]byte, []int) {
	return file_keyserver_v1_service_proto_rawDescGZIP(), []int{0}
}

func (x *GenerateKeyRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *GenerateKeyRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GenerateKeyRequest) GetOrgId() string {
	if x != nil {
		return x.OrgId
	}
	return ""
}

func (x *GenerateKeyRequest) GetScopes() []string {
	if x != nil {
		return x.Scopes
	}
	return nil
}

func (x *GenerateKeyRequest) GetIssuedByUserId() string {
	if x != nil {
		return x.IssuedByUserId
	}
	return ""
}

func (x *GenerateKeyRequest) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

func (x *GenerateKeyRequest) GetSharedDb() bool {
	if x != nil {
		return x.SharedDb
	}
	return false
}

type GenerateKeyResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ApiKey         string                 `protobuf:"bytes,1,opt,name=api_key,json=apiKey,proto3" json:"api_key,omitempty"`
	KeyId          string                 `protobuf:"bytes,2,opt,name=key_id,json=keyId,proto3" json:"key_id,omitempty"`
	TenantId       string                 `protobuf:"bytes,3,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	UserId         string                 `protobuf:"bytes,4,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	OrgId          string                 `protobuf:"bytes,5,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	CreatedAt      *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Scopes         []string               `protobuf:"bytes,7,rep,name=scopes,proto3" json:"scopes,omitempty"`
	OwnerType      string                 `protobuf:"bytes,8,opt,name=owner_type,json=ownerType,proto3" json:"owner_type,omitempty"`
	OwnerId        string                 `protobuf:"bytes,9,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	IssuedByUserId string                 `protobuf:"bytes,10,opt,name=issued_by_user_id,json=issuedByUserId,proto3" json:"issued_by_user_id,omitempty"`
	ExpiresAt      *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	SharedDb       bool                   `protobuf:"varint,12,opt,name=shared_db,json=sharedDb,proto3" json:"shared_db,omitempty"`
	Valid          bool                   `protobuf:"varint,13,opt,name=valid,proto3" json:"valid,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GenerateKeyResponse) Reset() {
	*x = GenerateKeyResponse{}
	mi := &file_keyserver_v1_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateKeyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateKeyResponse) ProtoMessage() {}

func (x *GenerateKeyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_keyserver_v1_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateKeyResponse.ProtoReflect.Descriptor instead.
func (*GenerateKeyResponse) Descriptor() ([]byte, []int) {
	return file_keyserver_v1_service_proto_rawDescGZIP(), []int{1}
}

func (x *GenerateKeyResponse) GetApiKey() string {
	if x != nil {
		return x.ApiKey
	}
	return ""
}

func (x *GenerateKeyResponse) GetKeyId() string {
	if x != nil {
		return x.KeyId
	}
	return ""
}

func (x *GenerateKeyResponse) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *GenerateKeyResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GenerateKeyResponse) GetOrgId() string {
	if x != nil {
		return x.OrgId
	}
	return ""
}

func (x *GenerateKeyResponse) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *GenerateKeyResponse) GetScopes() []string {
	if x != nil {
		return x.Scopes
	}
	return nil
}

func (x *GenerateKeyResponse) GetOwnerType() string {
	if x != nil {
		return x.OwnerType
	}
	return ""
}

func (x *GenerateKeyResponse) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

func (x *GenerateKeyResponse) GetIssuedByUserId() string {
	if x != nil {
		return x.IssuedByUserId
	}
	return ""
}

func (x *GenerateKeyResponse) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

func (x *GenerateKeyResponse) GetSharedDb() bool {
	if x != nil {
		return x.SharedDb
	}
	return false
}

func (x *GenerateKeyResponse) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

type PutTenantDatabaseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Enterprise    bool                   `protobuf:"varint,2,opt,name=enterprise,proto3" json:"enterprise,omitempty"`
	Database      *DatabaseDetails       `protobuf:"bytes,3,opt,name=database,proto3" json:"database,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutTenantDatabaseRequest) Reset() {
	*x = PutTenantDatabaseRequest{}
	mi := &file_keyserver_v1_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutTenantDatabaseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutTenantDatabaseRequest) ProtoMessage() {}

func (x *PutTenantDatabaseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_keyserver_v1_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutTenantDatabaseRequest.ProtoReflect.Descriptor instead.
func (*PutTenantDatabaseRequest) Descriptor() ([]byte, []int) {
	return file_keyserver_v1_service_proto_rawDescGZIP(), []int{2}
}

func (x *PutTenantDatabaseRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *PutTenantDatabaseRequest) GetEnterprise() bool {
	if x != nil {
		return x.Enterprise
	}
	return false
}

func (x *PutTenantDatabaseRequest) GetDatabase() *DatabaseDetails {
	if x != nil {
		return x.Database
	}
	return nil
}

type PutTenantDatabaseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Enterprise    bool                   `protobuf:"varint,2,opt,name=enterprise,proto3" json:"enterprise,omitempty"`
	Database      *DatabaseDetails       `protobuf:"bytes,3,opt,name=database,proto3" json:"database,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutTenantDatabaseResponse) Reset() {
	*x = PutTenantDatabaseResponse{}
	mi := &file_keyserver_v1_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutTenantDatabaseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutTenantDatabaseResponse) ProtoMessage() {}

func (x *PutTenantDatabaseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_keyserver_v1_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutTenantDatabaseResponse.ProtoReflect.Descriptor instead.
func (*PutTenantDatabaseResponse) Descriptor() ([]byte, []int) {
	return file_keyserver_v1_service_proto_rawDescGZIP(), []int{3}
}

func (x *PutTenantDatabaseResponse) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *PutTenantDatabaseResponse) GetEnterprise() bool {
	if x != nil {
		return x.Enterprise
	}
	return false
}

func (x *PutTenantDatabaseResponse) GetDatabase() *DatabaseDetails {
	if x != nil {
		return x.Database
	}
	return nil
}

type ValidateKeyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ApiKey        string                 `protobuf:"bytes,1,opt,name=api_key,json=apiKey,proto3" json:"api_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateKeyRequest) Reset() {
	*x = ValidateKeyRequest{}
	mi := &file_keyserver_v1_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateKeyRequest) ProtoMessage() {}

func (x *ValidateKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_keyserver_v1_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateKeyRequest.ProtoReflect.Descriptor instead.
func (*ValidateKeyRequest) Descriptor() ([]byte, []int) {
	return file_keyserver_v1_service_proto_rawDescGZIP(), []int{4}
}

func (x *ValidateKeyRequest) GetApiKey() string {
	if x != nil {
		return x.ApiKey
	}
	return ""
}

type ValidateKeyResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	KeyId          string                 `protobuf:"bytes,1,opt,name=key_id,json=keyId,proto3" json:"key_id,omitempty"`
	TenantId       string                 `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	UserId         string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	OrgId          string                 `protobuf:"bytes,4,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	Database       *DatabaseDetails       `protobuf:"bytes,5,opt,name=database,proto3" json:"database,omitempty"`
	Scopes         []string               `protobuf:"bytes,6,rep,name=scopes,proto3" json:"scopes,omitempty"`
	OwnerType      string                 `protobuf:"bytes,7,opt,name=owner_type,json=ownerType,proto3" json:"owner_type,omitempty"`
	OwnerId        string                 `protobuf:"bytes,8,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	IssuedByUserId string                 `protobuf:"bytes,9,opt,name=issued_by_user_id,json=issuedByUserId,proto3" json:"issued_by_user_id,omitempty"`
	ExpiresAt      *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	SharedDb       bool                   `protobuf:"varint,11,opt,name=shared_db,json=sharedDb,proto3" json:"shared_db,omitempty"`
	Valid          bool                   `protobuf:"varint,12,opt,name=valid,proto3" json:"valid,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ValidateKeyResponse) Reset() {
	*x = ValidateKeyResponse{}
	mi := &file_keyserver_v1_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateKeyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateKeyResponse) ProtoMessage() {}

func (x *ValidateKeyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_keyserver_v1_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateKeyResponse.ProtoReflect.Descriptor instead.
func (*ValidateKeyResponse) Descriptor() ([]byte, []int) {
	return file_keyserver_v1_service_proto_rawDescGZIP(), []int{5}
}

func (x *ValidateKeyResponse) GetKeyId() string {
	if x != nil {
		return x.KeyId
	}
	return ""
}

func (x *ValidateKeyResponse) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *ValidateKeyResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ValidateKeyResponse) GetOrgId() string {
	if x != nil {
		return x.OrgId
	}
	return ""
}

func (x *ValidateKeyResponse) GetDatabase() *DatabaseDetails {
	if x != nil {
		return x.Database
	}
	return nil
}

func (x *ValidateKeyResponse) GetScopes() []string {
	if x != nil {
		return x.Scopes
	}
	return nil
}

func (x *ValidateKeyResponse) GetOwnerType() string {
	if x != nil {
		return x.OwnerType
	}
	return ""
}

func (x *ValidateKeyResponse) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

func (x *ValidateKeyResponse) GetIssuedByUserId() string {
	if x != nil {
		return x.IssuedByUserId
	}
	return ""
}

func (x *ValidateKeyResponse) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

func (x *ValidateKeyResponse) GetSharedDb() bool {
	if x != nil {
		return x.SharedDb
	}
	return false
}

func (x *ValidateKeyResponse) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

type DatabaseDetails struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Engine        string                 `protobuf:"bytes,1,opt,name=engine,proto3" json:"engine,omitempty"`
	Host          string                 `protobuf:"bytes,2,opt,name=host,proto3" json:"host,omitempty"`
	Port          uint32                 `protobuf:"varint,3,opt,name=port,proto3" json:"port,omitempty"`
	Database      string                 `protobuf:"bytes,4,opt,name=database,proto3" json:"database,omitempty"`
	Username      string                 `protobuf:"bytes,5,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,6,opt,name=password,proto3" json:"password,omitempty"`
	SslMode       string                 `protobuf:"bytes,7,opt,name=ssl_mode,json=sslMode,proto3" json:"ssl_mode,omitempty"`
	Dedicated     bool                   `protobuf:"varint,8,opt,name=dedicated,proto3" json:"dedicated,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DatabaseDetails) Reset() {
	*x = DatabaseDetails{}
	mi := &file_keyserver_v1_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DatabaseDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DatabaseDetails) ProtoMessage() {}

func (x *DatabaseDetails) ProtoReflect() protoreflect.Message {
	mi := &file_keyserver_v1_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DatabaseDetails.ProtoReflect.Descriptor instead.
func (*DatabaseDetails) Descriptor() ([]byte, []int) {
	return file_keyserver_v1_service_proto_rawDescGZIP(), []int{6}
}

func (x *DatabaseDetails) GetEngine() string {
	if x != nil {
		return x.Engine
	}
	return ""
}

func (x *DatabaseDetails) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *DatabaseDetails) GetPort() uint32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *DatabaseDetails) GetDatabase() string {
	if x != nil {
		return x.Database
	}
	return ""
}

func (x *DatabaseDetails) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *DatabaseDetails) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *DatabaseDetails) GetSslMode() string {
	if x != nil {
		return x.SslMode
	}
	return ""
}

func (x *DatabaseDetails) GetDedicated() bool {
	if x != nil {
		return x.Dedicated
	}
	return false
}

type HealthzRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthzRequest) Reset() {
	*x = HealthzRequest{}
	mi := &file_keyserver_v1_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthzRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthzRequest) ProtoMessage() {}

func (x *HealthzRequest) ProtoReflect() protoreflect.Message {
	mi := &file_keyserver_v1_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthzRequest.ProtoReflect.Descriptor instead.
func (*HealthzRequest) Descriptor() ([]byte, []int) {
	return file_keyserver_v1_service_proto_rawDescGZIP(), []int{7}
}

type HealthzResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthzResponse) Reset() {
	*x = HealthzResponse{}
	mi := &file_keyserver_v1_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthzResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthzResponse) ProtoMessage() {}

func (x *HealthzResponse) ProtoReflect() protoreflect.Message {
	mi := &file_keyserver_v1_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthzResponse.ProtoReflect.Descriptor instead.
func (*HealthzResponse) Descriptor() ([]byte, []int) {
	return file_keyserver_v1_service_proto_rawDescGZIP(), []int{8}
}

func (x *HealthzResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_keyserver_v1_service_proto protoreflect.FileDescriptor

const file_keyserver_v1_service_proto_rawDesc = "" +
	"\n" +
	"\x1akeyserver/v1/service.proto\x12\fkeyserver.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xfc\x01\n" +
	"\x12GenerateKeyRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x15\n" +
	"\x06org_id\x18\x03 \x01(\tR\x05orgId\x12\x16\n" +
	"\x06scopes\x18\x04 \x03(\tR\x06scopes\x12)\n" +
	"\x11issued_by_user_id\x18\x05 \x01(\tR\x0eissuedByUserId\x129\n" +
	"\n" +
	"expires_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\x12\x1b\n" +
	"\tshared_db\x18\a \x01(\bR\bsharedDb\"\xb8\x03\n" +
	"\x13GenerateKeyResponse\x12\x17\n" +
	"\aapi_key\x18\x01 \x01(\tR\x06apiKey\x12\x15\n" +
	"\x06key_id\x18\x02 \x01(\tR\x05keyId\x12\x1b\n" +
	"\ttenant_id\x18\x03 \x01(\tR\btenantId\x12\x17\n" +
	"\auser_id\x18\x04 \x01(\tR\x06userId\x12\x15\n" +
	"\x06org_id\x18\x05 \x01(\tR\x05orgId\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12\x16\n" +
	"\x06scopes\x18\a \x03(\tR\x06scopes\x12\x1d\n" +
	"\n" +
	"owner_type\x18\b \x01(\tR\townerType\x12\x19\n" +
	"\bowner_id\x18\t \x01(\tR\aownerId\x12)\n" +
	"\x11issued_by_user_id\x18\n" +
	" \x01(\tR\x0eissuedByUserId\x129\n" +
	"\n" +
	"expires_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\x12\x1b\n" +
	"\tshared_db\x18\f \x01(\bR\bsharedDb\x12\x14\n" +
	"\x05valid\x18\r \x01(\bR\x05valid\"\x92\x01\n" +
	"\x18PutTenantDatabaseRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x1e\n" +
	"\n" +
	"enterprise\x18\x02 \x01(\bR\n" +
	"enterprise\x129\n" +
	"\bdatabase\x18\x03 \x01(\v2\x1d.keyserver.v1.DatabaseDetailsR\bdatabase\"\x93\x01\n" +
	"\x19PutTenantDatabaseResponse\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x1e\n" +
	"\n" +
	"enterprise\x18\x02 \x01(\bR\n" +
	"enterprise\x129\n" +
	"\bdatabase\x18\x03 \x01(\v2\x1d.keyserver.v1.DatabaseDetailsR\bdatabase\"-\n" +
	"\x12ValidateKeyRequest\x12\x17\n" +
	"\aapi_key\x18\x01 \x01(\tR\x06apiKey\"\x9f\x03\n" +
	"\x13ValidateKeyResponse\x12\x15\n" +
	"\x06key_id\x18\x01 \x01(\tR\x05keyId\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\tR\btenantId\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\x12\x15\n" +
	"\x06org_id\x18\x04 \x01(\tR\x05orgId\x129\n" +
	"\bdatabase\x18\x05 \x01(\v2\x1d.keyserver.v1.DatabaseDetailsR\bdatabase\x12\x16\n" +
	"\x06scopes\x18\x06 \x03(\tR\x06scopes\x12\x1d\n" +
	"\n" +
	"owner_type\x18\a \x01(\tR\townerType\x12\x19\n" +
	"\bowner_id\x18\b \x01(\tR\aownerId\x12)\n" +
	"\x11issued_by_user_id\x18\t \x01(\tR\x0eissuedByUserId\x129\n" +
	"\n" +
	"expires_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\x12\x1b\n" +
	"\tshared_db\x18\v \x01(\bR\bsharedDb\x12\x14\n" +
	"\x05valid\x18\f \x01(\bR\x05valid\"\xde\x01\n" +
	"\x0fDatabaseDetails\x12\x16\n" +
	"\x06engine\x18\x01 \x01(\tR\x06engine\x12\x12\n" +
	"\x04host\x18\x02 \x01(\tR\x04host\x12\x12\n" +
	"\x04port\x18\x03 \x01(\rR\x04port\x12\x1a\n" +
	"\bdatabase\x18\x04 \x01(\tR\bdatabase\x12\x1a\n" +
	"\busername\x18\x05 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x06 \x01(\tR\bpassword\x12\x19\n" +
	"\bssl_mode\x18\a \x01(\tR\asslMode\x12\x1c\n" +
	"\tdedicated\x18\b \x01(\bR\tdedicated\"\x10\n" +
	"\x0eHealthzRequest\")\n" +
	"\x0fHealthzResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status2\xe2\x02\n" +
	"\n" +
	"KeyService\x12R\n" +
	"\vGenerateKey\x12 .keyserver.v1.GenerateKeyRequest\x1a!.keyserver.v1.GenerateKeyResponse\x12d\n" +
	"\x11PutTenantDatabase\x12&.keyserver.v1.PutTenantDatabaseRequest\x1a'.keyserver.v1.PutTenantDatabaseResponse\x12R\n" +
	"\vValidateKey\x12 .keyserver.v1.ValidateKeyRequest\x1a!.keyserver.v1.ValidateKeyResponse\x12F\n" +
	"\aHealthz\x12\x1c.keyserver.v1.HealthzRequest\x1a\x1d.keyserver.v1.HealthzResponseB9Z7github.com/policies2/protobufs/keyserver/v1;keyserverv1b\x06proto3"

var (
	file_keyserver_v1_service_proto_rawDescOnce sync.Once
	file_keyserver_v1_service_proto_rawDescData []byte
)

func file_keyserver_v1_service_proto_rawDescGZIP() []byte {
	file_keyserver_v1_service_proto_rawDescOnce.Do(func() {
		file_keyserver_v1_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_keyserver_v1_service_proto_rawDesc), len(file_keyserver_v1_service_proto_rawDesc)))
	})
	return file_keyserver_v1_service_proto_rawDescData
}

var file_keyserver_v1_service_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_keyserver_v1_service_proto_goTypes = []any{
	(*GenerateKeyRequest)(nil),        // 0: keyserver.v1.GenerateKeyRequest
	(*GenerateKeyResponse)(nil),       // 1: keyserver.v1.GenerateKeyResponse
	(*PutTenantDatabaseRequest)(nil),  // 2: keyserver.v1.PutTenantDatabaseRequest
	(*PutTenantDatabaseResponse)(nil), // 3: keyserver.v1.PutTenantDatabaseResponse
	(*ValidateKeyRequest)(nil),        // 4: keyserver.v1.ValidateKeyRequest
	(*ValidateKeyResponse)(nil),       // 5: keyserver.v1.ValidateKeyResponse
	(*DatabaseDetails)(nil),           // 6: keyserver.v1.DatabaseDetails
	(*HealthzRequest)(nil),            // 7: keyserver.v1.HealthzRequest
	(*HealthzResponse)(nil),           // 8: keyserver.v1.HealthzResponse
	(*timestamppb.Timestamp)(nil),     // 9: google.protobuf.Timestamp
}
var file_keyserver_v1_service_proto_depIdxs = []int32{
	9,  // 0: keyserver.v1.GenerateKeyRequest.expires_at:type_name -> google.protobuf.Timestamp
	9,  // 1: keyserver.v1.GenerateKeyResponse.created_at:type_name -> google.protobuf.Timestamp
	9,  // 2: keyserver.v1.GenerateKeyResponse.expires_at:type_name -> google.protobuf.Timestamp
	6,  // 3: keyserver.v1.PutTenantDatabaseRequest.database:type_name -> keyserver.v1.DatabaseDetails
	6,  // 4: keyserver.v1.PutTenantDatabaseResponse.database:type_name -> keyserver.v1.DatabaseDetails
	6,  // 5: keyserver.v1.ValidateKeyResponse.database:type_name -> keyserver.v1.DatabaseDetails
	9,  // 6: keyserver.v1.ValidateKeyResponse.expires_at:type_name -> google.protobuf.Timestamp
	0,  // 7: keyserver.v1.KeyService.GenerateKey:input_type -> keyserver.v1.GenerateKeyRequest
	2,  // 8: keyserver.v1.KeyService.PutTenantDatabase:input_type -> keyserver.v1.PutTenantDatabaseRequest
	4,  // 9: keyserver.v1.KeyService.ValidateKey:input_type -> keyserver.v1.ValidateKeyRequest
	7,  // 10: keyserver.v1.KeyService.Healthz:input_type -> keyserver.v1.HealthzRequest
	1,  // 11: keyserver.v1.KeyService.GenerateKey:output_type -> keyserver.v1.GenerateKeyResponse
	3,  // 12: keyserver.v1.KeyService.PutTenantDatabase:output_type -> keyserver.v1.PutTenantDatabaseResponse
	5,  // 13: keyserver.v1.KeyService.ValidateKey:output_type -> keyserver.v1.ValidateKeyResponse
	8,  // 14: keyserver.v1.KeyService.Healthz:output_type -> keyserver.v1.HealthzResponse
	11, // [11:15] is the sub-list for method output_type
	7,  // [7:11] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_keyserver_v1_service_proto_init() }
func file_keyserver_v1_service_proto_init() {
	if File_keyserver_v1_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_keyserver_v1_service_proto_rawDesc), len(file_keyserver_v1_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_keyserver_v1_service_proto_goTypes,
		DependencyIndexes: file_keyserver_v1_service_proto_depIdxs,
		MessageInfos:      file_keyserver_v1_service_proto_msgTypes,
	}.Build()
	File_keyserver_v1_service_proto = out.File
	file_keyserver_v1_service_proto_goTypes = nil
	file_keyserver_v1_service_proto_depIdxs = nil
}
