// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: provisioner/v1/service.proto

package provisionerv1

import (
	v1 "github.com/policies2/protobufs/keyserver/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ProvisionTenantDatabaseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	ServiceName   string                 `protobuf:"bytes,2,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	AllowExisting bool                   `protobuf:"varint,3,opt,name=allow_existing,json=allowExisting,proto3" json:"allow_existing,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProvisionTenantDatabaseRequest) Reset() {
	*x = ProvisionTenantDatabaseRequest{}
	mi := &file_provisioner_v1_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProvisionTenantDatabaseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProvisionTenantDatabaseRequest) ProtoMessage() {}

func (x *ProvisionTenantDatabaseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_provisioner_v1_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProvisionTenantDatabaseRequest.ProtoReflect.Descriptor instead.
func (*ProvisionTenantDatabaseRequest) Descriptor() ([]byte, []int) {
	return file_provisioner_v1_service_proto_rawDescGZIP(), []int{0}
}

func (x *ProvisionTenantDatabaseRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *ProvisionTenantDatabaseRequest) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *ProvisionTenantDatabaseRequest) GetAllowExisting() bool {
	if x != nil {
		return x.AllowExisting
	}
	return false
}

type ProvisionTenantDatabaseResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	TenantId         string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	RailwayService   string                 `protobuf:"bytes,2,opt,name=railway_service,json=railwayService,proto3" json:"railway_service,omitempty"`
	Database         *v1.DatabaseDetails    `protobuf:"bytes,3,opt,name=database,proto3" json:"database,omitempty"`
	MigrationApplied bool                   `protobuf:"varint,4,opt,name=migration_applied,json=migrationApplied,proto3" json:"migration_applied,omitempty"`
	AlreadyExisted   bool                   `protobuf:"varint,5,opt,name=already_existed,json=alreadyExisted,proto3" json:"already_existed,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ProvisionTenantDatabaseResponse) Reset() {
	*x = ProvisionTenantDatabaseResponse{}
	mi := &file_provisioner_v1_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProvisionTenantDatabaseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProvisionTenantDatabaseResponse) ProtoMessage() {}

func (x *ProvisionTenantDatabaseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_provisioner_v1_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProvisionTenantDatabaseResponse.ProtoReflect.Descriptor instead.
func (*ProvisionTenantDatabaseResponse) Descriptor() ([]byte, []int) {
	return file_provisioner_v1_service_proto_rawDescGZIP(), []int{1}
}

func (x *ProvisionTenantDatabaseResponse) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *ProvisionTenantDatabaseResponse) GetRailwayService() string {
	if x != nil {
		return x.RailwayService
	}
	return ""
}

func (x *ProvisionTenantDatabaseResponse) GetDatabase() *v1.DatabaseDetails {
	if x != nil {
		return x.Database
	}
	return nil
}

func (x *ProvisionTenantDatabaseResponse) GetMigrationApplied() bool {
	if x != nil {
		return x.MigrationApplied
	}
	return false
}

func (x *ProvisionTenantDatabaseResponse) GetAlreadyExisted() bool {
	if x != nil {
		return x.AlreadyExisted
	}
	return false
}

type HealthzRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthzRequest) Reset() {
	*x = HealthzRequest{}
	mi := &file_provisioner_v1_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthzRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthzRequest) ProtoMessage() {}

func (x *HealthzRequest) ProtoReflect() protoreflect.Message {
	mi := &file_provisioner_v1_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthzRequest.ProtoReflect.Descriptor instead.
func (*HealthzRequest) Descriptor() ([]byte, []int) {
	return file_provisioner_v1_service_proto_rawDescGZIP(), []int{2}
}

type HealthzResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthzResponse) Reset() {
	*x = HealthzResponse{}
	mi := &file_provisioner_v1_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthzResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthzResponse) ProtoMessage() {}

func (x *HealthzResponse) ProtoReflect() protoreflect.Message {
	mi := &file_provisioner_v1_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthzResponse.ProtoReflect.Descriptor instead.
func (*HealthzResponse) Descriptor() ([]byte, []int) {
	return file_provisioner_v1_service_proto_rawDescGZIP(), []int{3}
}

func (x *HealthzResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type MigrateTenantDatabaseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MigrateTenantDatabaseRequest) Reset() {
	*x = MigrateTenantDatabaseRequest{}
	mi := &file_provisioner_v1_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MigrateTenantDatabaseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MigrateTenantDatabaseRequest) ProtoMessage() {}

func (x *MigrateTenantDatabaseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_provisioner_v1_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MigrateTenantDatabaseRequest.ProtoReflect.Descriptor instead.
func (*MigrateTenantDatabaseRequest) Descriptor() ([]byte, []int) {
	return file_provisioner_v1_service_proto_rawDescGZIP(), []int{4}
}

func (x *MigrateTenantDatabaseRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

type MigrateTenantDatabaseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MigrateTenantDatabaseResponse) Reset() {
	*x = MigrateTenantDatabaseResponse{}
	mi := &file_provisioner_v1_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MigrateTenantDatabaseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MigrateTenantDatabaseResponse) ProtoMessage() {}

func (x *MigrateTenantDatabaseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_provisioner_v1_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MigrateTenantDatabaseResponse.ProtoReflect.Descriptor instead.
func (*MigrateTenantDatabaseResponse) Descriptor() ([]byte, []int) {
	return file_provisioner_v1_service_proto_rawDescGZIP(), []int{5}
}

func (x *MigrateTenantDatabaseResponse) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *MigrateTenantDatabaseResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_provisioner_v1_service_proto protoreflect.FileDescriptor

const file_provisioner_v1_service_proto_rawDesc = "" +
	"\n" +
	"\x1cprovisioner/v1/service.proto\x12\x0eprovisioner.v1\x1a\x1akeyserver/v1/service.proto\"\x87\x01\n" +
	"\x1eProvisionTenantDatabaseRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12!\n" +
	"\fservice_name\x18\x02 \x01(\tR\vserviceName\x12%\n" +
	"\x0eallow_existing\x18\x03 \x01(\bR\rallowExisting\"\xf8\x01\n" +
	"\x1fProvisionTenantDatabaseResponse\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12'\n" +
	"\x0frailway_service\x18\x02 \x01(\tR\x0erailwayService\x129\n" +
	"\bdatabase\x18\x03 \x01(\v2\x1d.keyserver.v1.DatabaseDetailsR\bdatabase\x12+\n" +
	"\x11migration_applied\x18\x04 \x01(\bR\x10migrationApplied\x12'\n" +
	"\x0falready_existed\x18\x05 \x01(\bR\x0ealreadyExisted\"\x10\n" +
	"\x0eHealthzRequest\")\n" +
	"\x0fHealthzResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\";\n" +
	"\x1cMigrateTenantDatabaseRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\"V\n" +
	"\x1dMigrateTenantDatabaseResponse\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess2\xe3\x01\n" +
	"\x19TenantProvisioningService\x12z\n" +
	"\x17ProvisionTenantDatabase\x12..provisioner.v1.ProvisionTenantDatabaseRequest\x1a/.provisioner.v1.ProvisionTenantDatabaseResponse\x12J\n" +
	"\aHealthz\x12\x1e.provisioner.v1.HealthzRequest\x1a\x1f.provisioner.v1.HealthzResponse2\x8e\x01\n" +
	"\x16TenantMigrationService\x12t\n" +
	"\x15MigrateTenantDatabase\x12,.provisioner.v1.MigrateTenantDatabaseRequest\x1a-.provisioner.v1.MigrateTenantDatabaseResponseB=Z;github.com/policies2/protobufs/provisioner/v1;provisionerv1b\x06proto3"

var (
	file_provisioner_v1_service_proto_rawDescOnce sync.Once
	file_provisioner_v1_service_proto_rawDescData []byte
)

func file_provisioner_v1_service_proto_rawDescGZIP() []byte {
	file_provisioner_v1_service_proto_rawDescOnce.Do(func() {
		file_provisioner_v1_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_provisioner_v1_service_proto_rawDesc), len(file_provisioner_v1_service_proto_rawDesc)))
	})
	return file_provisioner_v1_service_proto_rawDescData
}

var file_provisioner_v1_service_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_provisioner_v1_service_proto_goTypes = []any{
	(*ProvisionTenantDatabaseRequest)(nil),  // 0: provisioner.v1.ProvisionTenantDatabaseRequest
	(*ProvisionTenantDatabaseResponse)(nil), // 1: provisioner.v1.ProvisionTenantDatabaseResponse
	(*HealthzRequest)(nil),                  // 2: provisioner.v1.HealthzRequest
	(*HealthzResponse)(nil),                 // 3: provisioner.v1.HealthzResponse
	(*MigrateTenantDatabaseRequest)(nil),    // 4: provisioner.v1.MigrateTenantDatabaseRequest
	(*MigrateTenantDatabaseResponse)(nil),   // 5: provisioner.v1.MigrateTenantDatabaseResponse
	(*v1.DatabaseDetails)(nil),              // 6: keyserver.v1.DatabaseDetails
}
var file_provisioner_v1_service_proto_depIdxs = []int32{
	6, // 0: provisioner.v1.ProvisionTenantDatabaseResponse.database:type_name -> keyserver.v1.DatabaseDetails
	0, // 1: provisioner.v1.TenantProvisioningService.ProvisionTenantDatabase:input_type -> provisioner.v1.ProvisionTenantDatabaseRequest
	2, // 2: provisioner.v1.TenantProvisioningService.Healthz:input_type -> provisioner.v1.HealthzRequest
	4, // 3: provisioner.v1.TenantMigrationService.MigrateTenantDatabase:input_type -> provisioner.v1.MigrateTenantDatabaseRequest
	1, // 4: provisioner.v1.TenantProvisioningService.ProvisionTenantDatabase:output_type -> provisioner.v1.ProvisionTenantDatabaseResponse
	3, // 5: provisioner.v1.TenantProvisioningService.Healthz:output_type -> provisioner.v1.HealthzResponse
	5, // 6: provisioner.v1.TenantMigrationService.MigrateTenantDatabase:output_type -> provisioner.v1.MigrateTenantDatabaseResponse
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_provisioner_v1_service_proto_init() }
func file_provisioner_v1_service_proto_init() {
	if File_provisioner_v1_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_provisioner_v1_service_proto_rawDesc), len(file_provisioner_v1_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_provisioner_v1_service_proto_goTypes,
		DependencyIndexes: file_provisioner_v1_service_proto_depIdxs,
		MessageInfos:      file_provisioner_v1_service_proto_msgTypes,
	}.Build()
	File_provisioner_v1_service_proto = out.File
	file_provisioner_v1_service_proto_goTypes = nil
	file_provisioner_v1_service_proto_depIdxs = nil
}
