// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: billing/v1/service.proto

package billingv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Plan struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	PlanId            string                 `protobuf:"bytes,1,opt,name=plan_id,json=planId,proto3" json:"plan_id,omitempty"`
	MonthlyAllowance  int64                  `protobuf:"varint,2,opt,name=monthly_allowance,json=monthlyAllowance,proto3" json:"monthly_allowance,omitempty"`
	BaseGracePercent  int64                  `protobuf:"varint,3,opt,name=base_grace_percent,json=baseGracePercent,proto3" json:"base_grace_percent,omitempty"`
	DefaultLeaseUnits int64                  `protobuf:"varint,4,opt,name=default_lease_units,json=defaultLeaseUnits,proto3" json:"default_lease_units,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Plan) Reset() {
	*x = Plan{}
	mi := &file_billing_v1_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Plan) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Plan) ProtoMessage() {}

func (x *Plan) ProtoReflect() protoreflect.Message {
	mi := &file_billing_v1_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Plan.ProtoReflect.Descriptor instead.
func (*Plan) Descriptor() ([]byte, []int) {
	return file_billing_v1_service_proto_rawDescGZIP(), []int{0}
}

func (x *Plan) GetPlanId() string {
	if x != nil {
		return x.PlanId
	}
	return ""
}

func (x *Plan) GetMonthlyAllowance() int64 {
	if x != nil {
		return x.MonthlyAllowance
	}
	return 0
}

func (x *Plan) GetBaseGracePercent() int64 {
	if x != nil {
		return x.BaseGracePercent
	}
	return 0
}

func (x *Plan) GetDefaultLeaseUnits() int64 {
	if x != nil {
		return x.DefaultLeaseUnits
	}
	return 0
}

type UsageState struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	PeriodStartUtc string                 `protobuf:"bytes,1,opt,name=period_start_utc,json=periodStartUtc,proto3" json:"period_start_utc,omitempty"`
	UsedUnits      int64                  `protobuf:"varint,2,opt,name=used_units,json=usedUnits,proto3" json:"used_units,omitempty"`
	ReservedUnits  int64                  `protobuf:"varint,3,opt,name=reserved_units,json=reservedUnits,proto3" json:"reserved_units,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UsageState) Reset() {
	*x = UsageState{}
	mi := &file_billing_v1_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UsageState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UsageState) ProtoMessage() {}

func (x *UsageState) ProtoReflect() protoreflect.Message {
	mi := &file_billing_v1_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UsageState.ProtoReflect.Descriptor instead.
func (*UsageState) Descriptor() ([]byte, []int) {
	return file_billing_v1_service_proto_rawDescGZIP(), []int{1}
}

func (x *UsageState) GetPeriodStartUtc() string {
	if x != nil {
		return x.PeriodStartUtc
	}
	return ""
}

func (x *UsageState) GetUsedUnits() int64 {
	if x != nil {
		return x.UsedUnits
	}
	return 0
}

func (x *UsageState) GetReservedUnits() int64 {
	if x != nil {
		return x.ReservedUnits
	}
	return 0
}

type Account struct {
	state                     protoimpl.MessageState `protogen:"open.v1"`
	OrgId                     string                 `protobuf:"bytes,1,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	Plan                      *Plan                  `protobuf:"bytes,2,opt,name=plan,proto3" json:"plan,omitempty"`
	Current                   *UsageState            `protobuf:"bytes,3,opt,name=current,proto3" json:"current,omitempty"`
	GracePercent              int64                  `protobuf:"varint,4,opt,name=grace_percent,json=gracePercent,proto3" json:"grace_percent,omitempty"`
	GraceAllowance            int64                  `protobuf:"varint,5,opt,name=grace_allowance,json=graceAllowance,proto3" json:"grace_allowance,omitempty"`
	AvailableUnits            int64                  `protobuf:"varint,6,opt,name=available_units,json=availableUnits,proto3" json:"available_units,omitempty"`
	OverageUsedThisPeriod     bool                   `protobuf:"varint,7,opt,name=overage_used_this_period,json=overageUsedThisPeriod,proto3" json:"overage_used_this_period,omitempty"`
	ConsecutiveGracePenalties int32                  `protobuf:"varint,8,opt,name=consecutive_grace_penalties,json=consecutiveGracePenalties,proto3" json:"consecutive_grace_penalties,omitempty"`
	CleanMonthsSinceOverage   int32                  `protobuf:"varint,9,opt,name=clean_months_since_overage,json=cleanMonthsSinceOverage,proto3" json:"clean_months_since_overage,omitempty"`
	UpdatedAtUtc              string                 `protobuf:"bytes,10,opt,name=updated_at_utc,json=updatedAtUtc,proto3" json:"updated_at_utc,omitempty"`
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *Account) Reset() {
	*x = Account{}
	mi := &file_billing_v1_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Account) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Account) ProtoMessage() {}

func (x *Account) ProtoReflect() protoreflect.Message {
	mi := &file_billing_v1_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Account.ProtoReflect.Descriptor instead.
func (*Account) Descriptor() ([]byte, []int) {
	return file_billing_v1_service_proto_rawDescGZIP(), []int{2}
}

func (x *Account) GetOrgId() string {
	if x != nil {
		return x.OrgId
	}
	return ""
}

func (x *Account) GetPlan() *Plan {
	if x != nil {
		return x.Plan
	}
	return nil
}

func (x *Account) GetCurrent() *UsageState {
	if x != nil {
		return x.Current
	}
	return nil
}

func (x *Account) GetGracePercent() int64 {
	if x != nil {
		return x.GracePercent
	}
	return 0
}

func (x *Account) GetGraceAllowance() int64 {
	if x != nil {
		return x.GraceAllowance
	}
	return 0
}

func (x *Account) GetAvailableUnits() int64 {
	if x != nil {
		return x.AvailableUnits
	}
	return 0
}

func (x *Account) GetOverageUsedThisPeriod() bool {
	if x != nil {
		return x.OverageUsedThisPeriod
	}
	return false
}

func (x *Account) GetConsecutiveGracePenalties() int32 {
	if x != nil {
		return x.ConsecutiveGracePenalties
	}
	return 0
}

func (x *Account) GetCleanMonthsSinceOverage() int32 {
	if x != nil {
		return x.CleanMonthsSinceOverage
	}
	return 0
}

func (x *Account) GetUpdatedAtUtc() string {
	if x != nil {
		return x.UpdatedAtUtc
	}
	return ""
}

type UpsertAccountRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	OrgId              string                 `protobuf:"bytes,1,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	PlanId             string                 `protobuf:"bytes,2,opt,name=plan_id,json=planId,proto3" json:"plan_id,omitempty"`
	MonthlyAllowance   int64                  `protobuf:"varint,3,opt,name=monthly_allowance,json=monthlyAllowance,proto3" json:"monthly_allowance,omitempty"`
	BaseGracePercent   int64                  `protobuf:"varint,4,opt,name=base_grace_percent,json=baseGracePercent,proto3" json:"base_grace_percent,omitempty"`
	DefaultLeaseUnits  int64                  `protobuf:"varint,5,opt,name=default_lease_units,json=defaultLeaseUnits,proto3" json:"default_lease_units,omitempty"`
	CurrentUsedUnits   int64                  `protobuf:"varint,6,opt,name=current_used_units,json=currentUsedUnits,proto3" json:"current_used_units,omitempty"`
	CurrentPeriodStart string                 `protobuf:"bytes,7,opt,name=current_period_start,json=currentPeriodStart,proto3" json:"current_period_start,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *UpsertAccountRequest) Reset() {
	*x = UpsertAccountRequest{}
	mi := &file_billing_v1_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpsertAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertAccountRequest) ProtoMessage() {}

func (x *UpsertAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_billing_v1_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsertAccountRequest.ProtoReflect.Descriptor instead.
func (*UpsertAccountRequest) Descriptor() ([]byte, []int) {
	return file_billing_v1_service_proto_rawDescGZIP(), []int{3}
}

func (x *UpsertAccountRequest) GetOrgId() string {
	if x != nil {
		return x.OrgId
	}
	return ""
}

func (x *UpsertAccountRequest) GetPlanId() string {
	if x != nil {
		return x.PlanId
	}
	return ""
}

func (x *UpsertAccountRequest) GetMonthlyAllowance() int64 {
	if x != nil {
		return x.MonthlyAllowance
	}
	return 0
}

func (x *UpsertAccountRequest) GetBaseGracePercent() int64 {
	if x != nil {
		return x.BaseGracePercent
	}
	return 0
}

func (x *UpsertAccountRequest) GetDefaultLeaseUnits() int64 {
	if x != nil {
		return x.DefaultLeaseUnits
	}
	return 0
}

func (x *UpsertAccountRequest) GetCurrentUsedUnits() int64 {
	if x != nil {
		return x.CurrentUsedUnits
	}
	return 0
}

func (x *UpsertAccountRequest) GetCurrentPeriodStart() string {
	if x != nil {
		return x.CurrentPeriodStart
	}
	return ""
}

type GetAccountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrgId         string                 `protobuf:"bytes,1,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAccountRequest) Reset() {
	*x = GetAccountRequest{}
	mi := &file_billing_v1_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAccountRequest) ProtoMessage() {}

func (x *GetAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_billing_v1_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAccountRequest.ProtoReflect.Descriptor instead.
func (*GetAccountRequest) Descriptor() ([]byte, []int) {
	return file_billing_v1_service_proto_rawDescGZIP(), []int{4}
}

func (x *GetAccountRequest) GetOrgId() string {
	if x != nil {
		return x.OrgId
	}
	return ""
}

type UpsertAccountResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Account       *Account               `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	Status        *string                `protobuf:"bytes,99,opt,name=status,proto3,oneof" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpsertAccountResponse) Reset() {
	*x = UpsertAccountResponse{}
	mi := &file_billing_v1_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpsertAccountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertAccountResponse) ProtoMessage() {}

func (x *UpsertAccountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_billing_v1_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsertAccountResponse.ProtoReflect.Descriptor instead.
func (*UpsertAccountResponse) Descriptor() ([]byte, []int) {
	return file_billing_v1_service_proto_rawDescGZIP(), []int{5}
}

func (x *UpsertAccountResponse) GetAccount() *Account {
	if x != nil {
		return x.Account
	}
	return nil
}

func (x *UpsertAccountResponse) GetStatus() string {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return ""
}

type GetAccountResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Account       *Account               `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	Status        *string                `protobuf:"bytes,99,opt,name=status,proto3,oneof" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAccountResponse) Reset() {
	*x = GetAccountResponse{}
	mi := &file_billing_v1_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAccountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAccountResponse) ProtoMessage() {}

func (x *GetAccountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_billing_v1_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAccountResponse.ProtoReflect.Descriptor instead.
func (*GetAccountResponse) Descriptor() ([]byte, []int) {
	return file_billing_v1_service_proto_rawDescGZIP(), []int{6}
}

func (x *GetAccountResponse) GetAccount() *Account {
	if x != nil {
		return x.Account
	}
	return nil
}

func (x *GetAccountResponse) GetStatus() string {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return ""
}

type Lease struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	LeaseId          string                 `protobuf:"bytes,1,opt,name=lease_id,json=leaseId,proto3" json:"lease_id,omitempty"`
	OrgId            string                 `protobuf:"bytes,2,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	KeyId            string                 `protobuf:"bytes,3,opt,name=key_id,json=keyId,proto3" json:"key_id,omitempty"`
	KeyKind          string                 `protobuf:"bytes,4,opt,name=key_kind,json=keyKind,proto3" json:"key_kind,omitempty"`
	ReservedUnits    int64                  `protobuf:"varint,5,opt,name=reserved_units,json=reservedUnits,proto3" json:"reserved_units,omitempty"`
	ConsumedUnits    int64                  `protobuf:"varint,6,opt,name=consumed_units,json=consumedUnits,proto3" json:"consumed_units,omitempty"`
	RemainingUnits   int64                  `protobuf:"varint,7,opt,name=remaining_units,json=remainingUnits,proto3" json:"remaining_units,omitempty"`
	ExpiresAtUtc     string                 `protobuf:"bytes,8,opt,name=expires_at_utc,json=expiresAtUtc,proto3" json:"expires_at_utc,omitempty"`
	PeriodStartUtc   string                 `protobuf:"bytes,9,opt,name=period_start_utc,json=periodStartUtc,proto3" json:"period_start_utc,omitempty"`
	Released         bool                   `protobuf:"varint,10,opt,name=released,proto3" json:"released,omitempty"`
	Counted          bool                   `protobuf:"varint,11,opt,name=counted,proto3" json:"counted,omitempty"`
	IdempotencyCount int32                  `protobuf:"varint,12,opt,name=idempotency_count,json=idempotencyCount,proto3" json:"idempotency_count,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Lease) Reset() {
	*x = Lease{}
	mi := &file_billing_v1_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Lease) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Lease) ProtoMessage() {}

func (x *Lease) ProtoReflect() protoreflect.Message {
	mi := &file_billing_v1_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Lease.ProtoReflect.Descriptor instead.
func (*Lease) Descriptor() ([]byte, []int) {
	return file_billing_v1_service_proto_rawDescGZIP(), []int{7}
}

func (x *Lease) GetLeaseId() string {
	if x != nil {
		return x.LeaseId
	}
	return ""
}

func (x *Lease) GetOrgId() string {
	if x != nil {
		return x.OrgId
	}
	return ""
}

func (x *Lease) GetKeyId() string {
	if x != nil {
		return x.KeyId
	}
	return ""
}

func (x *Lease) GetKeyKind() string {
	if x != nil {
		return x.KeyKind
	}
	return ""
}

func (x *Lease) GetReservedUnits() int64 {
	if x != nil {
		return x.ReservedUnits
	}
	return 0
}

func (x *Lease) GetConsumedUnits() int64 {
	if x != nil {
		return x.ConsumedUnits
	}
	return 0
}

func (x *Lease) GetRemainingUnits() int64 {
	if x != nil {
		return x.RemainingUnits
	}
	return 0
}

func (x *Lease) GetExpiresAtUtc() string {
	if x != nil {
		return x.ExpiresAtUtc
	}
	return ""
}

func (x *Lease) GetPeriodStartUtc() string {
	if x != nil {
		return x.PeriodStartUtc
	}
	return ""
}

func (x *Lease) GetReleased() bool {
	if x != nil {
		return x.Released
	}
	return false
}

func (x *Lease) GetCounted() bool {
	if x != nil {
		return x.Counted
	}
	return false
}

func (x *Lease) GetIdempotencyCount() int32 {
	if x != nil {
		return x.IdempotencyCount
	}
	return 0
}

type AuthorizeLeaseRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	OrgId          string                 `protobuf:"bytes,1,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	KeyId          string                 `protobuf:"bytes,2,opt,name=key_id,json=keyId,proto3" json:"key_id,omitempty"`
	KeyKind        string                 `protobuf:"bytes,3,opt,name=key_kind,json=keyKind,proto3" json:"key_kind,omitempty"`
	RequestedUnits int64                  `protobuf:"varint,4,opt,name=requested_units,json=requestedUnits,proto3" json:"requested_units,omitempty"`
	TtlSeconds     int64                  `protobuf:"varint,5,opt,name=ttl_seconds,json=ttlSeconds,proto3" json:"ttl_seconds,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AuthorizeLeaseRequest) Reset() {
	*x = AuthorizeLeaseRequest{}
	mi := &file_billing_v1_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthorizeLeaseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthorizeLeaseRequest) ProtoMessage() {}

func (x *AuthorizeLeaseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_billing_v1_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthorizeLeaseRequest.ProtoReflect.Descriptor instead.
func (*AuthorizeLeaseRequest) Descriptor() ([]byte, []int) {
	return file_billing_v1_service_proto_rawDescGZIP(), []int{8}
}

func (x *AuthorizeLeaseRequest) GetOrgId() string {
	if x != nil {
		return x.OrgId
	}
	return ""
}

func (x *AuthorizeLeaseRequest) GetKeyId() string {
	if x != nil {
		return x.KeyId
	}
	return ""
}

func (x *AuthorizeLeaseRequest) GetKeyKind() string {
	if x != nil {
		return x.KeyKind
	}
	return ""
}

func (x *AuthorizeLeaseRequest) GetRequestedUnits() int64 {
	if x != nil {
		return x.RequestedUnits
	}
	return 0
}

func (x *AuthorizeLeaseRequest) GetTtlSeconds() int64 {
	if x != nil {
		return x.TtlSeconds
	}
	return 0
}

type AuthorizeLeaseResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Allowed        bool                   `protobuf:"varint,1,opt,name=allowed,proto3" json:"allowed,omitempty"`
	Counted        bool                   `protobuf:"varint,2,opt,name=counted,proto3" json:"counted,omitempty"`
	DenialReason   string                 `protobuf:"bytes,3,opt,name=denial_reason,json=denialReason,proto3" json:"denial_reason,omitempty"`
	Lease          *Lease                 `protobuf:"bytes,4,opt,name=lease,proto3" json:"lease,omitempty"`
	Account        *Account               `protobuf:"bytes,5,opt,name=account,proto3" json:"account,omitempty"`
	GrantedUnits   int64                  `protobuf:"varint,6,opt,name=granted_units,json=grantedUnits,proto3" json:"granted_units,omitempty"`
	RequestedUnits int64                  `protobuf:"varint,7,opt,name=requested_units,json=requestedUnits,proto3" json:"requested_units,omitempty"`
	RemainingUnits int64                  `protobuf:"varint,8,opt,name=remaining_units,json=remainingUnits,proto3" json:"remaining_units,omitempty"`
	Message        string                 `protobuf:"bytes,9,opt,name=message,proto3" json:"message,omitempty"`
	Status         *string                `protobuf:"bytes,99,opt,name=status,proto3,oneof" json:"status,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AuthorizeLeaseResponse) Reset() {
	*x = AuthorizeLeaseResponse{}
	mi := &file_billing_v1_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthorizeLeaseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthorizeLeaseResponse) ProtoMessage() {}

func (x *AuthorizeLeaseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_billing_v1_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthorizeLeaseResponse.ProtoReflect.Descriptor instead.
func (*AuthorizeLeaseResponse) Descriptor() ([]byte, []int) {
	return file_billing_v1_service_proto_rawDescGZIP(), []int{9}
}

func (x *AuthorizeLeaseResponse) GetAllowed() bool {
	if x != nil {
		return x.Allowed
	}
	return false
}

func (x *AuthorizeLeaseResponse) GetCounted() bool {
	if x != nil {
		return x.Counted
	}
	return false
}

func (x *AuthorizeLeaseResponse) GetDenialReason() string {
	if x != nil {
		return x.DenialReason
	}
	return ""
}

func (x *AuthorizeLeaseResponse) GetLease() *Lease {
	if x != nil {
		return x.Lease
	}
	return nil
}

func (x *AuthorizeLeaseResponse) GetAccount() *Account {
	if x != nil {
		return x.Account
	}
	return nil
}

func (x *AuthorizeLeaseResponse) GetGrantedUnits() int64 {
	if x != nil {
		return x.GrantedUnits
	}
	return 0
}

func (x *AuthorizeLeaseResponse) GetRequestedUnits() int64 {
	if x != nil {
		return x.RequestedUnits
	}
	return 0
}

func (x *AuthorizeLeaseResponse) GetRemainingUnits() int64 {
	if x != nil {
		return x.RemainingUnits
	}
	return 0
}

func (x *AuthorizeLeaseResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *AuthorizeLeaseResponse) GetStatus() string {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return ""
}

type RecordUsageRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	LeaseId        string                 `protobuf:"bytes,1,opt,name=lease_id,json=leaseId,proto3" json:"lease_id,omitempty"`
	UsedUnits      int64                  `protobuf:"varint,2,opt,name=used_units,json=usedUnits,proto3" json:"used_units,omitempty"`
	IdempotencyKey string                 `protobuf:"bytes,3,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RecordUsageRequest) Reset() {
	*x = RecordUsageRequest{}
	mi := &file_billing_v1_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecordUsageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordUsageRequest) ProtoMessage() {}

func (x *RecordUsageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_billing_v1_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordUsageRequest.ProtoReflect.Descriptor instead.
func (*RecordUsageRequest) Descriptor() ([]byte, []int) {
	return file_billing_v1_service_proto_rawDescGZIP(), []int{10}
}

func (x *RecordUsageRequest) GetLeaseId() string {
	if x != nil {
		return x.LeaseId
	}
	return ""
}

func (x *RecordUsageRequest) GetUsedUnits() int64 {
	if x != nil {
		return x.UsedUnits
	}
	return 0
}

func (x *RecordUsageRequest) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

type RecordUsageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Lease         *Lease                 `protobuf:"bytes,1,opt,name=lease,proto3" json:"lease,omitempty"`
	Account       *Account               `protobuf:"bytes,2,opt,name=account,proto3" json:"account,omitempty"`
	Idempotent    bool                   `protobuf:"varint,3,opt,name=idempotent,proto3" json:"idempotent,omitempty"`
	Status        *string                `protobuf:"bytes,99,opt,name=status,proto3,oneof" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecordUsageResponse) Reset() {
	*x = RecordUsageResponse{}
	mi := &file_billing_v1_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecordUsageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordUsageResponse) ProtoMessage() {}

func (x *RecordUsageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_billing_v1_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordUsageResponse.ProtoReflect.Descriptor instead.
func (*RecordUsageResponse) Descriptor() ([]byte, []int) {
	return file_billing_v1_service_proto_rawDescGZIP(), []int{11}
}

func (x *RecordUsageResponse) GetLease() *Lease {
	if x != nil {
		return x.Lease
	}
	return nil
}

func (x *RecordUsageResponse) GetAccount() *Account {
	if x != nil {
		return x.Account
	}
	return nil
}

func (x *RecordUsageResponse) GetIdempotent() bool {
	if x != nil {
		return x.Idempotent
	}
	return false
}

func (x *RecordUsageResponse) GetStatus() string {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return ""
}

type ReleaseLeaseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LeaseId       string                 `protobuf:"bytes,1,opt,name=lease_id,json=leaseId,proto3" json:"lease_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReleaseLeaseRequest) Reset() {
	*x = ReleaseLeaseRequest{}
	mi := &file_billing_v1_service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReleaseLeaseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReleaseLeaseRequest) ProtoMessage() {}

func (x *ReleaseLeaseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_billing_v1_service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReleaseLeaseRequest.ProtoReflect.Descriptor instead.
func (*ReleaseLeaseRequest) Descriptor() ([]byte, []int) {
	return file_billing_v1_service_proto_rawDescGZIP(), []int{12}
}

func (x *ReleaseLeaseRequest) GetLeaseId() string {
	if x != nil {
		return x.LeaseId
	}
	return ""
}

type ReleaseLeaseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Lease         *Lease                 `protobuf:"bytes,1,opt,name=lease,proto3" json:"lease,omitempty"`
	Account       *Account               `protobuf:"bytes,2,opt,name=account,proto3" json:"account,omitempty"`
	ReleasedUnits int64                  `protobuf:"varint,3,opt,name=released_units,json=releasedUnits,proto3" json:"released_units,omitempty"`
	Status        *string                `protobuf:"bytes,99,opt,name=status,proto3,oneof" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReleaseLeaseResponse) Reset() {
	*x = ReleaseLeaseResponse{}
	mi := &file_billing_v1_service_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReleaseLeaseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReleaseLeaseResponse) ProtoMessage() {}

func (x *ReleaseLeaseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_billing_v1_service_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReleaseLeaseResponse.ProtoReflect.Descriptor instead.
func (*ReleaseLeaseResponse) Descriptor() ([]byte, []int) {
	return file_billing_v1_service_proto_rawDescGZIP(), []int{13}
}

func (x *ReleaseLeaseResponse) GetLease() *Lease {
	if x != nil {
		return x.Lease
	}
	return nil
}

func (x *ReleaseLeaseResponse) GetAccount() *Account {
	if x != nil {
		return x.Account
	}
	return nil
}

func (x *ReleaseLeaseResponse) GetReleasedUnits() int64 {
	if x != nil {
		return x.ReleasedUnits
	}
	return 0
}

func (x *ReleaseLeaseResponse) GetStatus() string {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return ""
}

type HealthzRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthzRequest) Reset() {
	*x = HealthzRequest{}
	mi := &file_billing_v1_service_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthzRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthzRequest) ProtoMessage() {}

func (x *HealthzRequest) ProtoReflect() protoreflect.Message {
	mi := &file_billing_v1_service_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthzRequest.ProtoReflect.Descriptor instead.
func (*HealthzRequest) Descriptor() ([]byte, []int) {
	return file_billing_v1_service_proto_rawDescGZIP(), []int{14}
}

type HealthzResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthzResponse) Reset() {
	*x = HealthzResponse{}
	mi := &file_billing_v1_service_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthzResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthzResponse) ProtoMessage() {}

func (x *HealthzResponse) ProtoReflect() protoreflect.Message {
	mi := &file_billing_v1_service_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthzResponse.ProtoReflect.Descriptor instead.
func (*HealthzResponse) Descriptor() ([]byte, []int) {
	return file_billing_v1_service_proto_rawDescGZIP(), []int{15}
}

func (x *HealthzResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_billing_v1_service_proto protoreflect.FileDescriptor

const file_billing_v1_service_proto_rawDesc = "" +
	"\n" +
	"\x18billing/v1/service.proto\x12\n" +
	"billing.v1\"\xaa\x01\n" +
	"\x04Plan\x12\x17\n" +
	"\aplan_id\x18\x01 \x01(\tR\x06planId\x12+\n" +
	"\x11monthly_allowance\x18\x02 \x01(\x03R\x10monthlyAllowance\x12,\n" +
	"\x12base_grace_percent\x18\x03 \x01(\x03R\x10baseGracePercent\x12.\n" +
	"\x13default_lease_units\x18\x04 \x01(\x03R\x11defaultLeaseUnits\"|\n" +
	"\n" +
	"UsageState\x12(\n" +
	"\x10period_start_utc\x18\x01 \x01(\tR\x0eperiodStartUtc\x12\x1d\n" +
	"\n" +
	"used_units\x18\x02 \x01(\x03R\tusedUnits\x12%\n" +
	"\x0ereserved_units\x18\x03 \x01(\x03R\rreservedUnits\"\xcb\x03\n" +
	"\aAccount\x12\x15\n" +
	"\x06org_id\x18\x01 \x01(\tR\x05orgId\x12$\n" +
	"\x04plan\x18\x02 \x01(\v2\x10.billing.v1.PlanR\x04plan\x120\n" +
	"\acurrent\x18\x03 \x01(\v2\x16.billing.v1.UsageStateR\acurrent\x12#\n" +
	"\rgrace_percent\x18\x04 \x01(\x03R\fgracePercent\x12'\n" +
	"\x0fgrace_allowance\x18\x05 \x01(\x03R\x0egraceAllowance\x12'\n" +
	"\x0favailable_units\x18\x06 \x01(\x03R\x0eavailableUnits\x127\n" +
	"\x18overage_used_this_period\x18\a \x01(\bR\x15overageUsedThisPeriod\x12>\n" +
	"\x1bconsecutive_grace_penalties\x18\b \x01(\x05R\x19consecutiveGracePenalties\x12;\n" +
	"\x1aclean_months_since_overage\x18\t \x01(\x05R\x17cleanMonthsSinceOverage\x12$\n" +
	"\x0eupdated_at_utc\x18\n" +
	" \x01(\tR\fupdatedAtUtc\"\xb1\x02\n" +
	"\x14UpsertAccountRequest\x12\x15\n" +
	"\x06org_id\x18\x01 \x01(\tR\x05orgId\x12\x17\n" +
	"\aplan_id\x18\x02 \x01(\tR\x06planId\x12+\n" +
	"\x11monthly_allowance\x18\x03 \x01(\x03R\x10monthlyAllowance\x12,\n" +
	"\x12base_grace_percent\x18\x04 \x01(\x03R\x10baseGracePercent\x12.\n" +
	"\x13default_lease_units\x18\x05 \x01(\x03R\x11defaultLeaseUnits\x12,\n" +
	"\x12current_used_units\x18\x06 \x01(\x03R\x10currentUsedUnits\x120\n" +
	"\x14current_period_start\x18\a \x01(\tR\x12currentPeriodStart\"*\n" +
	"\x11GetAccountRequest\x12\x15\n" +
	"\x06org_id\x18\x01 \x01(\tR\x05orgId\"n\n" +
	"\x15UpsertAccountResponse\x12-\n" +
	"\aaccount\x18\x01 \x01(\v2\x13.billing.v1.AccountR\aaccount\x12\x1b\n" +
	"\x06status\x18c \x01(\tH\x00R\x06status\x88\x01\x01B\t\n" +
	"\a_status\"k\n" +
	"\x12GetAccountResponse\x12-\n" +
	"\aaccount\x18\x01 \x01(\v2\x13.billing.v1.AccountR\aaccount\x12\x1b\n" +
	"\x06status\x18c \x01(\tH\x00R\x06status\x88\x01\x01B\t\n" +
	"\a_status\"\x95\x03\n" +
	"\x05Lease\x12\x19\n" +
	"\blease_id\x18\x01 \x01(\tR\aleaseId\x12\x15\n" +
	"\x06org_id\x18\x02 \x01(\tR\x05orgId\x12\x15\n" +
	"\x06key_id\x18\x03 \x01(\tR\x05keyId\x12\x19\n" +
	"\bkey_kind\x18\x04 \x01(\tR\akeyKind\x12%\n" +
	"\x0ereserved_units\x18\x05 \x01(\x03R\rreservedUnits\x12%\n" +
	"\x0econsumed_units\x18\x06 \x01(\x03R\rconsumedUnits\x12'\n" +
	"\x0fremaining_units\x18\a \x01(\x03R\x0eremainingUnits\x12$\n" +
	"\x0eexpires_at_utc\x18\b \x01(\tR\fexpiresAtUtc\x12(\n" +
	"\x10period_start_utc\x18\t \x01(\tR\x0eperiodStartUtc\x12\x1a\n" +
	"\breleased\x18\n" +
	" \x01(\bR\breleased\x12\x18\n" +
	"\acounted\x18\v \x01(\bR\acounted\x12+\n" +
	"\x11idempotency_count\x18\f \x01(\x05R\x10idempotencyCount\"\xaa\x01\n" +
	"\x15AuthorizeLeaseRequest\x12\x15\n" +
	"\x06org_id\x18\x01 \x01(\tR\x05orgId\x12\x15\n" +
	"\x06key_id\x18\x02 \x01(\tR\x05keyId\x12\x19\n" +
	"\bkey_kind\x18\x03 \x01(\tR\akeyKind\x12'\n" +
	"\x0frequested_units\x18\x04 \x01(\x03R\x0erequestedUnits\x12\x1f\n" +
	"\vttl_seconds\x18\x05 \x01(\x03R\n" +
	"ttlSeconds\"\x82\x03\n" +
	"\x16AuthorizeLeaseResponse\x12\x18\n" +
	"\aallowed\x18\x01 \x01(\bR\aallowed\x12\x18\n" +
	"\acounted\x18\x02 \x01(\bR\acounted\x12#\n" +
	"\rdenial_reason\x18\x03 \x01(\tR\fdenialReason\x12'\n" +
	"\x05lease\x18\x04 \x01(\v2\x11.billing.v1.LeaseR\x05lease\x12-\n" +
	"\aaccount\x18\x05 \x01(\v2\x13.billing.v1.AccountR\aaccount\x12#\n" +
	"\rgranted_units\x18\x06 \x01(\x03R\fgrantedUnits\x12'\n" +
	"\x0frequested_units\x18\a \x01(\x03R\x0erequestedUnits\x12'\n" +
	"\x0fremaining_units\x18\b \x01(\x03R\x0eremainingUnits\x12\x18\n" +
	"\amessage\x18\t \x01(\tR\amessage\x12\x1b\n" +
	"\x06status\x18c \x01(\tH\x00R\x06status\x88\x01\x01B\t\n" +
	"\a_status\"w\n" +
	"\x12RecordUsageRequest\x12\x19\n" +
	"\blease_id\x18\x01 \x01(\tR\aleaseId\x12\x1d\n" +
	"\n" +
	"used_units\x18\x02 \x01(\x03R\tusedUnits\x12'\n" +
	"\x0fidempotency_key\x18\x03 \x01(\tR\x0eidempotencyKey\"\xb5\x01\n" +
	"\x13RecordUsageResponse\x12'\n" +
	"\x05lease\x18\x01 \x01(\v2\x11.billing.v1.LeaseR\x05lease\x12-\n" +
	"\aaccount\x18\x02 \x01(\v2\x13.billing.v1.AccountR\aaccount\x12\x1e\n" +
	"\n" +
	"idempotent\x18\x03 \x01(\bR\n" +
	"idempotent\x12\x1b\n" +
	"\x06status\x18c \x01(\tH\x00R\x06status\x88\x01\x01B\t\n" +
	"\a_status\"0\n" +
	"\x13ReleaseLeaseRequest\x12\x19\n" +
	"\blease_id\x18\x01 \x01(\tR\aleaseId\"\xbd\x01\n" +
	"\x14ReleaseLeaseResponse\x12'\n" +
	"\x05lease\x18\x01 \x01(\v2\x11.billing.v1.LeaseR\x05lease\x12-\n" +
	"\aaccount\x18\x02 \x01(\v2\x13.billing.v1.AccountR\aaccount\x12%\n" +
	"\x0ereleased_units\x18\x03 \x01(\x03R\rreleasedUnits\x12\x1b\n" +
	"\x06status\x18c \x01(\tH\x00R\x06status\x88\x01\x01B\t\n" +
	"\a_status\"\x10\n" +
	"\x0eHealthzRequest\")\n" +
	"\x0fHealthzResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status2\xf3\x03\n" +
	"\x0eBillingService\x12T\n" +
	"\rUpsertAccount\x12 .billing.v1.UpsertAccountRequest\x1a!.billing.v1.UpsertAccountResponse\x12K\n" +
	"\n" +
	"GetAccount\x12\x1d.billing.v1.GetAccountRequest\x1a\x1e.billing.v1.GetAccountResponse\x12W\n" +
	"\x0eAuthorizeLease\x12!.billing.v1.AuthorizeLeaseRequest\x1a\".billing.v1.AuthorizeLeaseResponse\x12N\n" +
	"\vRecordUsage\x12\x1e.billing.v1.RecordUsageRequest\x1a\x1f.billing.v1.RecordUsageResponse\x12Q\n" +
	"\fReleaseLease\x12\x1f.billing.v1.ReleaseLeaseRequest\x1a .billing.v1.ReleaseLeaseResponse\x12B\n" +
	"\aHealthz\x12\x1a.billing.v1.HealthzRequest\x1a\x1b.billing.v1.HealthzResponseB5Z3github.com/policies2/protobufs/billing/v1;billingv1b\x06proto3"

var (
	file_billing_v1_service_proto_rawDescOnce sync.Once
	file_billing_v1_service_proto_rawDescData []byte
)

func file_billing_v1_service_proto_rawDescGZIP() []byte {
	file_billing_v1_service_proto_rawDescOnce.Do(func() {
		file_billing_v1_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_billing_v1_service_proto_rawDesc), len(file_billing_v1_service_proto_rawDesc)))
	})
	return file_billing_v1_service_proto_rawDescData
}

var file_billing_v1_service_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_billing_v1_service_proto_goTypes = []any{
	(*Plan)(nil),                   // 0: billing.v1.Plan
	(*UsageState)(nil),             // 1: billing.v1.UsageState
	(*Account)(nil),                // 2: billing.v1.Account
	(*UpsertAccountRequest)(nil),   // 3: billing.v1.UpsertAccountRequest
	(*GetAccountRequest)(nil),      // 4: billing.v1.GetAccountRequest
	(*UpsertAccountResponse)(nil),  // 5: billing.v1.UpsertAccountResponse
	(*GetAccountResponse)(nil),     // 6: billing.v1.GetAccountResponse
	(*Lease)(nil),                  // 7: billing.v1.Lease
	(*AuthorizeLeaseRequest)(nil),  // 8: billing.v1.AuthorizeLeaseRequest
	(*AuthorizeLeaseResponse)(nil), // 9: billing.v1.AuthorizeLeaseResponse
	(*RecordUsageRequest)(nil),     // 10: billing.v1.RecordUsageRequest
	(*RecordUsageResponse)(nil),    // 11: billing.v1.RecordUsageResponse
	(*ReleaseLeaseRequest)(nil),    // 12: billing.v1.ReleaseLeaseRequest
	(*ReleaseLeaseResponse)(nil),   // 13: billing.v1.ReleaseLeaseResponse
	(*HealthzRequest)(nil),         // 14: billing.v1.HealthzRequest
	(*HealthzResponse)(nil),        // 15: billing.v1.HealthzResponse
}
var file_billing_v1_service_proto_depIdxs = []int32{
	0,  // 0: billing.v1.Account.plan:type_name -> billing.v1.Plan
	1,  // 1: billing.v1.Account.current:type_name -> billing.v1.UsageState
	2,  // 2: billing.v1.UpsertAccountResponse.account:type_name -> billing.v1.Account
	2,  // 3: billing.v1.GetAccountResponse.account:type_name -> billing.v1.Account
	7,  // 4: billing.v1.AuthorizeLeaseResponse.lease:type_name -> billing.v1.Lease
	2,  // 5: billing.v1.AuthorizeLeaseResponse.account:type_name -> billing.v1.Account
	7,  // 6: billing.v1.RecordUsageResponse.lease:type_name -> billing.v1.Lease
	2,  // 7: billing.v1.RecordUsageResponse.account:type_name -> billing.v1.Account
	7,  // 8: billing.v1.ReleaseLeaseResponse.lease:type_name -> billing.v1.Lease
	2,  // 9: billing.v1.ReleaseLeaseResponse.account:type_name -> billing.v1.Account
	3,  // 10: billing.v1.BillingService.UpsertAccount:input_type -> billing.v1.UpsertAccountRequest
	4,  // 11: billing.v1.BillingService.GetAccount:input_type -> billing.v1.GetAccountRequest
	8,  // 12: billing.v1.BillingService.AuthorizeLease:input_type -> billing.v1.AuthorizeLeaseRequest
	10, // 13: billing.v1.BillingService.RecordUsage:input_type -> billing.v1.RecordUsageRequest
	12, // 14: billing.v1.BillingService.ReleaseLease:input_type -> billing.v1.ReleaseLeaseRequest
	14, // 15: billing.v1.BillingService.Healthz:input_type -> billing.v1.HealthzRequest
	5,  // 16: billing.v1.BillingService.UpsertAccount:output_type -> billing.v1.UpsertAccountResponse
	6,  // 17: billing.v1.BillingService.GetAccount:output_type -> billing.v1.GetAccountResponse
	9,  // 18: billing.v1.BillingService.AuthorizeLease:output_type -> billing.v1.AuthorizeLeaseResponse
	11, // 19: billing.v1.BillingService.RecordUsage:output_type -> billing.v1.RecordUsageResponse
	13, // 20: billing.v1.BillingService.ReleaseLease:output_type -> billing.v1.ReleaseLeaseResponse
	15, // 21: billing.v1.BillingService.Healthz:output_type -> billing.v1.HealthzResponse
	16, // [16:22] is the sub-list for method output_type
	10, // [10:16] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_billing_v1_service_proto_init() }
func file_billing_v1_service_proto_init() {
	if File_billing_v1_service_proto != nil {
		return
	}
	file_billing_v1_service_proto_msgTypes[5].OneofWrappers = []any{}
	file_billing_v1_service_proto_msgTypes[6].OneofWrappers = []any{}
	file_billing_v1_service_proto_msgTypes[9].OneofWrappers = []any{}
	file_billing_v1_service_proto_msgTypes[11].OneofWrappers = []any{}
	file_billing_v1_service_proto_msgTypes[13].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_billing_v1_service_proto_rawDesc), len(file_billing_v1_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_billing_v1_service_proto_goTypes,
		DependencyIndexes: file_billing_v1_service_proto_depIdxs,
		MessageInfos:      file_billing_v1_service_proto_msgTypes,
	}.Build()
	File_billing_v1_service_proto = out.File
	file_billing_v1_service_proto_goTypes = nil
	file_billing_v1_service_proto_depIdxs = nil
}
