// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: policy/v1/policy.proto

package policyv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RunRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rule          string                 `protobuf:"bytes,1,opt,name=rule,proto3" json:"rule,omitempty"`     // Policy rule (DSL)
	Data          *structpb.Struct       `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`     // Dynamic input data
	Tests         *structpb.Struct       `protobuf:"bytes,3,opt,name=tests,proto3" json:"tests,omitempty"`   // Optional test cases
	Schema        *structpb.Struct       `protobuf:"bytes,4,opt,name=schema,proto3" json:"schema,omitempty"` // Optional JSON schema
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunRequest) Reset() {
	*x = RunRequest{}
	mi := &file_policy_v1_policy_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunRequest) ProtoMessage() {}

func (x *RunRequest) ProtoReflect() protoreflect.Message {
	mi := &file_policy_v1_policy_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunRequest.ProtoReflect.Descriptor instead.
func (*RunRequest) Descriptor() ([]byte, []int) {
	return file_policy_v1_policy_proto_rawDescGZIP(), []int{0}
}

func (x *RunRequest) GetRule() string {
	if x != nil {
		return x.Rule
	}
	return ""
}

func (x *RunRequest) GetData() *structpb.Struct {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *RunRequest) GetTests() *structpb.Struct {
	if x != nil {
		return x.Tests
	}
	return nil
}

func (x *RunRequest) GetSchema() *structpb.Struct {
	if x != nil {
		return x.Schema
	}
	return nil
}

type RunPolicyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PolicyId      string                 `protobuf:"bytes,1,opt,name=policy_id,json=policyId,proto3" json:"policy_id,omitempty"` // Stored policy ID
	Data          *structpb.Struct       `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`                         // Input data to evaluate
	BaseId        string                 `protobuf:"bytes,3,opt,name=base_id,json=baseId,proto3" json:"base_id,omitempty"`       // Stored policy base ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunPolicyRequest) Reset() {
	*x = RunPolicyRequest{}
	mi := &file_policy_v1_policy_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunPolicyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunPolicyRequest) ProtoMessage() {}

func (x *RunPolicyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_policy_v1_policy_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunPolicyRequest.ProtoReflect.Descriptor instead.
func (*RunPolicyRequest) Descriptor() ([]byte, []int) {
	return file_policy_v1_policy_proto_rawDescGZIP(), []int{1}
}

func (x *RunPolicyRequest) GetPolicyId() string {
	if x != nil {
		return x.PolicyId
	}
	return ""
}

func (x *RunPolicyRequest) GetData() *structpb.Struct {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *RunPolicyRequest) GetBaseId() string {
	if x != nil {
		return x.BaseId
	}
	return ""
}

type RunResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        bool                   `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`      // Policy evaluation result
	Trace         *structpb.Struct       `protobuf:"bytes,2,opt,name=trace,proto3" json:"trace,omitempty"`         // Execution trace
	Rule          []string               `protobuf:"bytes,3,rep,name=rule,proto3" json:"rule,omitempty"`           // Executed rules
	Data          *structpb.Struct       `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`           // Output data
	Error         *structpb.Struct       `protobuf:"bytes,5,opt,name=error,proto3" json:"error,omitempty"`         // Errors if any
	Labels        *structpb.Struct       `protobuf:"bytes,6,opt,name=labels,proto3" json:"labels,omitempty"`       // Labels
	Execution     *ExecutionTiming       `protobuf:"bytes,7,opt,name=execution,proto3" json:"execution,omitempty"` // Timing breakdown
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunResponse) Reset() {
	*x = RunResponse{}
	mi := &file_policy_v1_policy_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunResponse) ProtoMessage() {}

func (x *RunResponse) ProtoReflect() protoreflect.Message {
	mi := &file_policy_v1_policy_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunResponse.ProtoReflect.Descriptor instead.
func (*RunResponse) Descriptor() ([]byte, []int) {
	return file_policy_v1_policy_proto_rawDescGZIP(), []int{2}
}

func (x *RunResponse) GetResult() bool {
	if x != nil {
		return x.Result
	}
	return false
}

func (x *RunResponse) GetTrace() *structpb.Struct {
	if x != nil {
		return x.Trace
	}
	return nil
}

func (x *RunResponse) GetRule() []string {
	if x != nil {
		return x.Rule
	}
	return nil
}

func (x *RunResponse) GetData() *structpb.Struct {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *RunResponse) GetError() *structpb.Struct {
	if x != nil {
		return x.Error
	}
	return nil
}

func (x *RunResponse) GetLabels() *structpb.Struct {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *RunResponse) GetExecution() *ExecutionTiming {
	if x != nil {
		return x.Execution
	}
	return nil
}

type RunPolicyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        bool                   `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`      // Policy evaluation result
	Trace         *structpb.Struct       `protobuf:"bytes,2,opt,name=trace,proto3" json:"trace,omitempty"`         // Execution trace
	Rule          []string               `protobuf:"bytes,3,rep,name=rule,proto3" json:"rule,omitempty"`           // Executed rules
	Data          *structpb.Struct       `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`           // Output data
	Error         *structpb.Struct       `protobuf:"bytes,5,opt,name=error,proto3" json:"error,omitempty"`         // Errors if any
	Labels        *structpb.Struct       `protobuf:"bytes,6,opt,name=labels,proto3" json:"labels,omitempty"`       // Labels
	Execution     *ExecutionTiming       `protobuf:"bytes,7,opt,name=execution,proto3" json:"execution,omitempty"` // Timing breakdown
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunPolicyResponse) Reset() {
	*x = RunPolicyResponse{}
	mi := &file_policy_v1_policy_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunPolicyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunPolicyResponse) ProtoMessage() {}

func (x *RunPolicyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_policy_v1_policy_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunPolicyResponse.ProtoReflect.Descriptor instead.
func (*RunPolicyResponse) Descriptor() ([]byte, []int) {
	return file_policy_v1_policy_proto_rawDescGZIP(), []int{3}
}

func (x *RunPolicyResponse) GetResult() bool {
	if x != nil {
		return x.Result
	}
	return false
}

func (x *RunPolicyResponse) GetTrace() *structpb.Struct {
	if x != nil {
		return x.Trace
	}
	return nil
}

func (x *RunPolicyResponse) GetRule() []string {
	if x != nil {
		return x.Rule
	}
	return nil
}

func (x *RunPolicyResponse) GetData() *structpb.Struct {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *RunPolicyResponse) GetError() *structpb.Struct {
	if x != nil {
		return x.Error
	}
	return nil
}

func (x *RunPolicyResponse) GetLabels() *structpb.Struct {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *RunPolicyResponse) GetExecution() *ExecutionTiming {
	if x != nil {
		return x.Execution
	}
	return nil
}

type ExecutionTiming struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Orchestrator  *OrchestratorTiming    `protobuf:"bytes,1,opt,name=orchestrator,proto3" json:"orchestrator,omitempty"`
	Engine        string                 `protobuf:"bytes,2,opt,name=engine,proto3" json:"engine,omitempty"` // Nanoseconds as string
	Total         string                 `protobuf:"bytes,3,opt,name=total,proto3" json:"total,omitempty"`   // Nanoseconds as string
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecutionTiming) Reset() {
	*x = ExecutionTiming{}
	mi := &file_policy_v1_policy_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecutionTiming) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecutionTiming) ProtoMessage() {}

func (x *ExecutionTiming) ProtoReflect() protoreflect.Message {
	mi := &file_policy_v1_policy_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecutionTiming.ProtoReflect.Descriptor instead.
func (*ExecutionTiming) Descriptor() ([]byte, []int) {
	return file_policy_v1_policy_proto_rawDescGZIP(), []int{4}
}

func (x *ExecutionTiming) GetOrchestrator() *OrchestratorTiming {
	if x != nil {
		return x.Orchestrator
	}
	return nil
}

func (x *ExecutionTiming) GetEngine() string {
	if x != nil {
		return x.Engine
	}
	return ""
}

func (x *ExecutionTiming) GetTotal() string {
	if x != nil {
		return x.Total
	}
	return ""
}

type OrchestratorTiming struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Go            string                 `protobuf:"bytes,1,opt,name=go,proto3" json:"go,omitempty"`             // Pure Go processing time
	Database      string                 `protobuf:"bytes,2,opt,name=database,proto3" json:"database,omitempty"` // Database query time
	Total         string                 `protobuf:"bytes,3,opt,name=total,proto3" json:"total,omitempty"`       // Total orchestrator time
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrchestratorTiming) Reset() {
	*x = OrchestratorTiming{}
	mi := &file_policy_v1_policy_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrchestratorTiming) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrchestratorTiming) ProtoMessage() {}

func (x *OrchestratorTiming) ProtoReflect() protoreflect.Message {
	mi := &file_policy_v1_policy_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrchestratorTiming.ProtoReflect.Descriptor instead.
func (*OrchestratorTiming) Descriptor() ([]byte, []int) {
	return file_policy_v1_policy_proto_rawDescGZIP(), []int{5}
}

func (x *OrchestratorTiming) GetGo() string {
	if x != nil {
		return x.Go
	}
	return ""
}

func (x *OrchestratorTiming) GetDatabase() string {
	if x != nil {
		return x.Database
	}
	return ""
}

func (x *OrchestratorTiming) GetTotal() string {
	if x != nil {
		return x.Total
	}
	return ""
}

type RunFlowRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FlowId        string                 `protobuf:"bytes,1,opt,name=flow_id,json=flowId,proto3" json:"flow_id,omitempty"` // Stored flow ID
	Data          *structpb.Struct       `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`                   // Dynamic input data
	BaseId        string                 `protobuf:"bytes,3,opt,name=base_id,json=baseId,proto3" json:"base_id,omitempty"` // Stored flow base ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunFlowRequest) Reset() {
	*x = RunFlowRequest{}
	mi := &file_policy_v1_policy_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunFlowRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunFlowRequest) ProtoMessage() {}

func (x *RunFlowRequest) ProtoReflect() protoreflect.Message {
	mi := &file_policy_v1_policy_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunFlowRequest.ProtoReflect.Descriptor instead.
func (*RunFlowRequest) Descriptor() ([]byte, []int) {
	return file_policy_v1_policy_proto_rawDescGZIP(), []int{6}
}

func (x *RunFlowRequest) GetFlowId() string {
	if x != nil {
		return x.FlowId
	}
	return ""
}

func (x *RunFlowRequest) GetData() *structpb.Struct {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *RunFlowRequest) GetBaseId() string {
	if x != nil {
		return x.BaseId
	}
	return ""
}

type TestFlowRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          *structpb.Struct       `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`                         // Test data
	FlowYaml      string                 `protobuf:"bytes,2,opt,name=flow_yaml,json=flowYaml,proto3" json:"flow_yaml,omitempty"` // Flow definition (YAML string)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TestFlowRequest) Reset() {
	*x = TestFlowRequest{}
	mi := &file_policy_v1_policy_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestFlowRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestFlowRequest) ProtoMessage() {}

func (x *TestFlowRequest) ProtoReflect() protoreflect.Message {
	mi := &file_policy_v1_policy_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestFlowRequest.ProtoReflect.Descriptor instead.
func (*TestFlowRequest) Descriptor() ([]byte, []int) {
	return file_policy_v1_policy_proto_rawDescGZIP(), []int{7}
}

func (x *TestFlowRequest) GetData() *structpb.Struct {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *TestFlowRequest) GetFlowYaml() string {
	if x != nil {
		return x.FlowYaml
	}
	return ""
}

type RunFlowResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        *structpb.Value        `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"` // Can be any type (bool, string, struct)
	NodeResponse  []*FlowNodeResponse    `protobuf:"bytes,2,rep,name=node_response,json=nodeResponse,proto3" json:"node_response,omitempty"`
	Execution     *FlowExecutionTiming   `protobuf:"bytes,3,opt,name=execution,proto3" json:"execution,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunFlowResponse) Reset() {
	*x = RunFlowResponse{}
	mi := &file_policy_v1_policy_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunFlowResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunFlowResponse) ProtoMessage() {}

func (x *RunFlowResponse) ProtoReflect() protoreflect.Message {
	mi := &file_policy_v1_policy_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunFlowResponse.ProtoReflect.Descriptor instead.
func (*RunFlowResponse) Descriptor() ([]byte, []int) {
	return file_policy_v1_policy_proto_rawDescGZIP(), []int{8}
}

func (x *RunFlowResponse) GetResult() *structpb.Value {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *RunFlowResponse) GetNodeResponse() []*FlowNodeResponse {
	if x != nil {
		return x.NodeResponse
	}
	return nil
}

func (x *RunFlowResponse) GetExecution() *FlowExecutionTiming {
	if x != nil {
		return x.Execution
	}
	return nil
}

type TestFlowResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        *structpb.Value        `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"` // Can be any type (bool, string, struct)
	NodeResponse  []*FlowNodeResponse    `protobuf:"bytes,2,rep,name=node_response,json=nodeResponse,proto3" json:"node_response,omitempty"`
	Execution     *FlowExecutionTiming   `protobuf:"bytes,3,opt,name=execution,proto3" json:"execution,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TestFlowResponse) Reset() {
	*x = TestFlowResponse{}
	mi := &file_policy_v1_policy_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestFlowResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestFlowResponse) ProtoMessage() {}

func (x *TestFlowResponse) ProtoReflect() protoreflect.Message {
	mi := &file_policy_v1_policy_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestFlowResponse.ProtoReflect.Descriptor instead.
func (*TestFlowResponse) Descriptor() ([]byte, []int) {
	return file_policy_v1_policy_proto_rawDescGZIP(), []int{9}
}

func (x *TestFlowResponse) GetResult() *structpb.Value {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *TestFlowResponse) GetNodeResponse() []*FlowNodeResponse {
	if x != nil {
		return x.NodeResponse
	}
	return nil
}

func (x *TestFlowResponse) GetExecution() *FlowExecutionTiming {
	if x != nil {
		return x.Execution
	}
	return nil
}

type FlowNodeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	NodeType      string                 `protobuf:"bytes,2,opt,name=node_type,json=nodeType,proto3" json:"node_type,omitempty"`
	Response      *RunResponse           `protobuf:"bytes,3,opt,name=response,proto3" json:"response,omitempty"`
	Execution     *FlowNodeExecution     `protobuf:"bytes,4,opt,name=execution,proto3" json:"execution,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FlowNodeResponse) Reset() {
	*x = FlowNodeResponse{}
	mi := &file_policy_v1_policy_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FlowNodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FlowNodeResponse) ProtoMessage() {}

func (x *FlowNodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_policy_v1_policy_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FlowNodeResponse.ProtoReflect.Descriptor instead.
func (*FlowNodeResponse) Descriptor() ([]byte, []int) {
	return file_policy_v1_policy_proto_rawDescGZIP(), []int{10}
}

func (x *FlowNodeResponse) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *FlowNodeResponse) GetNodeType() string {
	if x != nil {
		return x.NodeType
	}
	return ""
}

func (x *FlowNodeResponse) GetResponse() *RunResponse {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *FlowNodeResponse) GetExecution() *FlowNodeExecution {
	if x != nil {
		return x.Execution
	}
	return nil
}

type FlowNodeExecution struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Database      string                 `protobuf:"bytes,1,opt,name=database,proto3" json:"database,omitempty"` // Policy load time (nanoseconds)
	Engine        string                 `protobuf:"bytes,2,opt,name=engine,proto3" json:"engine,omitempty"`     // Policy execution time (nanoseconds)
	Total         string                 `protobuf:"bytes,3,opt,name=total,proto3" json:"total,omitempty"`       // Total node time (nanoseconds)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FlowNodeExecution) Reset() {
	*x = FlowNodeExecution{}
	mi := &file_policy_v1_policy_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FlowNodeExecution) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FlowNodeExecution) ProtoMessage() {}

func (x *FlowNodeExecution) ProtoReflect() protoreflect.Message {
	mi := &file_policy_v1_policy_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FlowNodeExecution.ProtoReflect.Descriptor instead.
func (*FlowNodeExecution) Descriptor() ([]byte, []int) {
	return file_policy_v1_policy_proto_rawDescGZIP(), []int{11}
}

func (x *FlowNodeExecution) GetDatabase() string {
	if x != nil {
		return x.Database
	}
	return ""
}

func (x *FlowNodeExecution) GetEngine() string {
	if x != nil {
		return x.Engine
	}
	return ""
}

func (x *FlowNodeExecution) GetTotal() string {
	if x != nil {
		return x.Total
	}
	return ""
}

type FlowExecutionTiming struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Orchestrator  string                 `protobuf:"bytes,1,opt,name=orchestrator,proto3" json:"orchestrator,omitempty"` // Flow management overhead
	Database      string                 `protobuf:"bytes,2,opt,name=database,proto3" json:"database,omitempty"`         // Total database time
	Engine        string                 `protobuf:"bytes,3,opt,name=engine,proto3" json:"engine,omitempty"`             // Total engine time
	Total         string                 `protobuf:"bytes,4,opt,name=total,proto3" json:"total,omitempty"`               // Total end-to-end time
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FlowExecutionTiming) Reset() {
	*x = FlowExecutionTiming{}
	mi := &file_policy_v1_policy_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FlowExecutionTiming) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FlowExecutionTiming) ProtoMessage() {}

func (x *FlowExecutionTiming) ProtoReflect() protoreflect.Message {
	mi := &file_policy_v1_policy_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FlowExecutionTiming.ProtoReflect.Descriptor instead.
func (*FlowExecutionTiming) Descriptor() ([]byte, []int) {
	return file_policy_v1_policy_proto_rawDescGZIP(), []int{12}
}

func (x *FlowExecutionTiming) GetOrchestrator() string {
	if x != nil {
		return x.Orchestrator
	}
	return ""
}

func (x *FlowExecutionTiming) GetDatabase() string {
	if x != nil {
		return x.Database
	}
	return ""
}

func (x *FlowExecutionTiming) GetEngine() string {
	if x != nil {
		return x.Engine
	}
	return ""
}

func (x *FlowExecutionTiming) GetTotal() string {
	if x != nil {
		return x.Total
	}
	return ""
}

var File_policy_v1_policy_proto protoreflect.FileDescriptor

const file_policy_v1_policy_proto_rawDesc = "" +
	"\n" +
	"\x16policy/v1/policy.proto\x12\tpolicy.v1\x1a\x1cgoogle/protobuf/struct.proto\"\xad\x01\n" +
	"\n" +
	"RunRequest\x12\x12\n" +
	"\x04rule\x18\x01 \x01(\tR\x04rule\x12+\n" +
	"\x04data\x18\x02 \x01(\v2\x17.google.protobuf.StructR\x04data\x12-\n" +
	"\x05tests\x18\x03 \x01(\v2\x17.google.protobuf.StructR\x05tests\x12/\n" +
	"\x06schema\x18\x04 \x01(\v2\x17.google.protobuf.StructR\x06schema\"u\n" +
	"\x10RunPolicyRequest\x12\x1b\n" +
	"\tpolicy_id\x18\x01 \x01(\tR\bpolicyId\x12+\n" +
	"\x04data\x18\x02 \x01(\v2\x17.google.protobuf.StructR\x04data\x12\x17\n" +
	"\abase_id\x18\x03 \x01(\tR\x06baseId\"\xaf\x02\n" +
	"\vRunResponse\x12\x16\n" +
	"\x06result\x18\x01 \x01(\bR\x06result\x12-\n" +
	"\x05trace\x18\x02 \x01(\v2\x17.google.protobuf.StructR\x05trace\x12\x12\n" +
	"\x04rule\x18\x03 \x03(\tR\x04rule\x12+\n" +
	"\x04data\x18\x04 \x01(\v2\x17.google.protobuf.StructR\x04data\x12-\n" +
	"\x05error\x18\x05 \x01(\v2\x17.google.protobuf.StructR\x05error\x12/\n" +
	"\x06labels\x18\x06 \x01(\v2\x17.google.protobuf.StructR\x06labels\x128\n" +
	"\texecution\x18\a \x01(\v2\x1a.policy.v1.ExecutionTimingR\texecution\"\xb5\x02\n" +
	"\x11RunPolicyResponse\x12\x16\n" +
	"\x06result\x18\x01 \x01(\bR\x06result\x12-\n" +
	"\x05trace\x18\x02 \x01(\v2\x17.google.protobuf.StructR\x05trace\x12\x12\n" +
	"\x04rule\x18\x03 \x03(\tR\x04rule\x12+\n" +
	"\x04data\x18\x04 \x01(\v2\x17.google.protobuf.StructR\x04data\x12-\n" +
	"\x05error\x18\x05 \x01(\v2\x17.google.protobuf.StructR\x05error\x12/\n" +
	"\x06labels\x18\x06 \x01(\v2\x17.google.protobuf.StructR\x06labels\x128\n" +
	"\texecution\x18\a \x01(\v2\x1a.policy.v1.ExecutionTimingR\texecution\"\x82\x01\n" +
	"\x0fExecutionTiming\x12A\n" +
	"\forchestrator\x18\x01 \x01(\v2\x1d.policy.v1.OrchestratorTimingR\forchestrator\x12\x16\n" +
	"\x06engine\x18\x02 \x01(\tR\x06engine\x12\x14\n" +
	"\x05total\x18\x03 \x01(\tR\x05total\"V\n" +
	"\x12OrchestratorTiming\x12\x0e\n" +
	"\x02go\x18\x01 \x01(\tR\x02go\x12\x1a\n" +
	"\bdatabase\x18\x02 \x01(\tR\bdatabase\x12\x14\n" +
	"\x05total\x18\x03 \x01(\tR\x05total\"o\n" +
	"\x0eRunFlowRequest\x12\x17\n" +
	"\aflow_id\x18\x01 \x01(\tR\x06flowId\x12+\n" +
	"\x04data\x18\x02 \x01(\v2\x17.google.protobuf.StructR\x04data\x12\x17\n" +
	"\abase_id\x18\x03 \x01(\tR\x06baseId\"[\n" +
	"\x0fTestFlowRequest\x12+\n" +
	"\x04data\x18\x01 \x01(\v2\x17.google.protobuf.StructR\x04data\x12\x1b\n" +
	"\tflow_yaml\x18\x02 \x01(\tR\bflowYaml\"\xc1\x01\n" +
	"\x0fRunFlowResponse\x12.\n" +
	"\x06result\x18\x01 \x01(\v2\x16.google.protobuf.ValueR\x06result\x12@\n" +
	"\rnode_response\x18\x02 \x03(\v2\x1b.policy.v1.FlowNodeResponseR\fnodeResponse\x12<\n" +
	"\texecution\x18\x03 \x01(\v2\x1e.policy.v1.FlowExecutionTimingR\texecution\"\xc2\x01\n" +
	"\x10TestFlowResponse\x12.\n" +
	"\x06result\x18\x01 \x01(\v2\x16.google.protobuf.ValueR\x06result\x12@\n" +
	"\rnode_response\x18\x02 \x03(\v2\x1b.policy.v1.FlowNodeResponseR\fnodeResponse\x12<\n" +
	"\texecution\x18\x03 \x01(\v2\x1e.policy.v1.FlowExecutionTimingR\texecution\"\xb8\x01\n" +
	"\x10FlowNodeResponse\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x1b\n" +
	"\tnode_type\x18\x02 \x01(\tR\bnodeType\x122\n" +
	"\bresponse\x18\x03 \x01(\v2\x16.policy.v1.RunResponseR\bresponse\x12:\n" +
	"\texecution\x18\x04 \x01(\v2\x1c.policy.v1.FlowNodeExecutionR\texecution\"]\n" +
	"\x11FlowNodeExecution\x12\x1a\n" +
	"\bdatabase\x18\x01 \x01(\tR\bdatabase\x12\x16\n" +
	"\x06engine\x18\x02 \x01(\tR\x06engine\x12\x14\n" +
	"\x05total\x18\x03 \x01(\tR\x05total\"\x83\x01\n" +
	"\x13FlowExecutionTiming\x12\"\n" +
	"\forchestrator\x18\x01 \x01(\tR\forchestrator\x12\x1a\n" +
	"\bdatabase\x18\x02 \x01(\tR\bdatabase\x12\x16\n" +
	"\x06engine\x18\x03 \x01(\tR\x06engine\x12\x14\n" +
	"\x05total\x18\x04 \x01(\tR\x05total2\x8d\x01\n" +
	"\rPolicyService\x124\n" +
	"\x03Run\x12\x15.policy.v1.RunRequest\x1a\x16.policy.v1.RunResponse\x12F\n" +
	"\tRunPolicy\x12\x1b.policy.v1.RunPolicyRequest\x1a\x1c.policy.v1.RunPolicyResponse2\x94\x01\n" +
	"\vFlowService\x12@\n" +
	"\aRunFlow\x12\x19.policy.v1.RunFlowRequest\x1a\x1a.policy.v1.RunFlowResponse\x12C\n" +
	"\bTestFlow\x12\x1a.policy.v1.TestFlowRequest\x1a\x1b.policy.v1.TestFlowResponseB3Z1github.com/policies2/protobufs/policy/v1;policyv1b\x06proto3"

var (
	file_policy_v1_policy_proto_rawDescOnce sync.Once
	file_policy_v1_policy_proto_rawDescData []byte
)

func file_policy_v1_policy_proto_rawDescGZIP() []byte {
	file_policy_v1_policy_proto_rawDescOnce.Do(func() {
		file_policy_v1_policy_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_policy_v1_policy_proto_rawDesc), len(file_policy_v1_policy_proto_rawDesc)))
	})
	return file_policy_v1_policy_proto_rawDescData
}

var file_policy_v1_policy_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_policy_v1_policy_proto_goTypes = []any{
	(*RunRequest)(nil),          // 0: policy.v1.RunRequest
	(*RunPolicyRequest)(nil),    // 1: policy.v1.RunPolicyRequest
	(*RunResponse)(nil),         // 2: policy.v1.RunResponse
	(*RunPolicyResponse)(nil),   // 3: policy.v1.RunPolicyResponse
	(*ExecutionTiming)(nil),     // 4: policy.v1.ExecutionTiming
	(*OrchestratorTiming)(nil),  // 5: policy.v1.OrchestratorTiming
	(*RunFlowRequest)(nil),      // 6: policy.v1.RunFlowRequest
	(*TestFlowRequest)(nil),     // 7: policy.v1.TestFlowRequest
	(*RunFlowResponse)(nil),     // 8: policy.v1.RunFlowResponse
	(*TestFlowResponse)(nil),    // 9: policy.v1.TestFlowResponse
	(*FlowNodeResponse)(nil),    // 10: policy.v1.FlowNodeResponse
	(*FlowNodeExecution)(nil),   // 11: policy.v1.FlowNodeExecution
	(*FlowExecutionTiming)(nil), // 12: policy.v1.FlowExecutionTiming
	(*structpb.Struct)(nil),     // 13: google.protobuf.Struct
	(*structpb.Value)(nil),      // 14: google.protobuf.Value
}
var file_policy_v1_policy_proto_depIdxs = []int32{
	13, // 0: policy.v1.RunRequest.data:type_name -> google.protobuf.Struct
	13, // 1: policy.v1.RunRequest.tests:type_name -> google.protobuf.Struct
	13, // 2: policy.v1.RunRequest.schema:type_name -> google.protobuf.Struct
	13, // 3: policy.v1.RunPolicyRequest.data:type_name -> google.protobuf.Struct
	13, // 4: policy.v1.RunResponse.trace:type_name -> google.protobuf.Struct
	13, // 5: policy.v1.RunResponse.data:type_name -> google.protobuf.Struct
	13, // 6: policy.v1.RunResponse.error:type_name -> google.protobuf.Struct
	13, // 7: policy.v1.RunResponse.labels:type_name -> google.protobuf.Struct
	4,  // 8: policy.v1.RunResponse.execution:type_name -> policy.v1.ExecutionTiming
	13, // 9: policy.v1.RunPolicyResponse.trace:type_name -> google.protobuf.Struct
	13, // 10: policy.v1.RunPolicyResponse.data:type_name -> google.protobuf.Struct
	13, // 11: policy.v1.RunPolicyResponse.error:type_name -> google.protobuf.Struct
	13, // 12: policy.v1.RunPolicyResponse.labels:type_name -> google.protobuf.Struct
	4,  // 13: policy.v1.RunPolicyResponse.execution:type_name -> policy.v1.ExecutionTiming
	5,  // 14: policy.v1.ExecutionTiming.orchestrator:type_name -> policy.v1.OrchestratorTiming
	13, // 15: policy.v1.RunFlowRequest.data:type_name -> google.protobuf.Struct
	13, // 16: policy.v1.TestFlowRequest.data:type_name -> google.protobuf.Struct
	14, // 17: policy.v1.RunFlowResponse.result:type_name -> google.protobuf.Value
	10, // 18: policy.v1.RunFlowResponse.node_response:type_name -> policy.v1.FlowNodeResponse
	12, // 19: policy.v1.RunFlowResponse.execution:type_name -> policy.v1.FlowExecutionTiming
	14, // 20: policy.v1.TestFlowResponse.result:type_name -> google.protobuf.Value
	10, // 21: policy.v1.TestFlowResponse.node_response:type_name -> policy.v1.FlowNodeResponse
	12, // 22: policy.v1.TestFlowResponse.execution:type_name -> policy.v1.FlowExecutionTiming
	2,  // 23: policy.v1.FlowNodeResponse.response:type_name -> policy.v1.RunResponse
	11, // 24: policy.v1.FlowNodeResponse.execution:type_name -> policy.v1.FlowNodeExecution
	0,  // 25: policy.v1.PolicyService.Run:input_type -> policy.v1.RunRequest
	1,  // 26: policy.v1.PolicyService.RunPolicy:input_type -> policy.v1.RunPolicyRequest
	6,  // 27: policy.v1.FlowService.RunFlow:input_type -> policy.v1.RunFlowRequest
	7,  // 28: policy.v1.FlowService.TestFlow:input_type -> policy.v1.TestFlowRequest
	2,  // 29: policy.v1.PolicyService.Run:output_type -> policy.v1.RunResponse
	3,  // 30: policy.v1.PolicyService.RunPolicy:output_type -> policy.v1.RunPolicyResponse
	8,  // 31: policy.v1.FlowService.RunFlow:output_type -> policy.v1.RunFlowResponse
	9,  // 32: policy.v1.FlowService.TestFlow:output_type -> policy.v1.TestFlowResponse
	29, // [29:33] is the sub-list for method output_type
	25, // [25:29] is the sub-list for method input_type
	25, // [25:25] is the sub-list for extension type_name
	25, // [25:25] is the sub-list for extension extendee
	0,  // [0:25] is the sub-list for field type_name
}

func init() { file_policy_v1_policy_proto_init() }
func file_policy_v1_policy_proto_init() {
	if File_policy_v1_policy_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_policy_v1_policy_proto_rawDesc), len(file_policy_v1_policy_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_policy_v1_policy_proto_goTypes,
		DependencyIndexes: file_policy_v1_policy_proto_depIdxs,
		MessageInfos:      file_policy_v1_policy_proto_msgTypes,
	}.Build()
	File_policy_v1_policy_proto = out.File
	file_policy_v1_policy_proto_goTypes = nil
	file_policy_v1_policy_proto_depIdxs = nil
}
