name: Release

on:
  release:
    types:
      - published

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Buf
        uses: bufbuild/buf-setup-action@v1

      - name: Generate Bindings
        run: buf generate

      - name: Package Proto Sources
        run: tar -czf protobufs-proto-${{ github.event.release.tag_name }}.tar.gz keyserver policy provisioner

      - name: Package Go Bindings
        run: tar -czf protobufs-go-${{ github.event.release.tag_name }}.tar.gz keyserver/v1/*.pb.go policy/v1/*.pb.go provisioner/v1/*.pb.go

      - name: Upload Release Assets
        uses: softprops/action-gh-release@v2
        with:
          files: |
            protobufs-proto-${{ github.event.release.tag_name }}.tar.gz
            protobufs-go-${{ github.event.release.tag_name }}.tar.gz
